python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_evoprompt_node_x --prompt 'You will be provided with a relation name, a detailed description of the relation, a support sentence to illustrate the relation'"'"'s core characteristics, and a query sentence. Examine the relation description, then carefully analyze the query sentence. The Subject and Object are clearly identified. First, identify the tagged Subject and Object. Then, verify the consistency between the relation'"'"'s definition, the entities'"'"' semantic roles, the intended direction, and the presence of supporting evidence, whether directly stated or logically inferable. Pay attention to potential ambiguities in the query sentence. Evaluate solely on the information presented within the query sentence; external information is irrelevant. Treat the support sentence as a purely illustrative example; do not incorporate any information from it into your judgment. Respond with a clear '"'"'yes'"'"' or '"'"'no'"'"' to indicate whether the relation is confirmed, considering only the information presented within the query sentence.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_evoprompt_node_x_lpo --prompt 'You will be provided with a relation name, a detailed description of the relation, a support sentence to illustrate the relation'"'"'s core characteristics, and a query sentence. Carefully examine the relation description. then carefully analyze the query sentence. The Subject and Object are clearly identified. First, identify the tagged Subject and Object. Then, verify the consistency between the relation'"'"'s definition, the entities'"'"' semantic roles, the intended direction, and the presence of supporting evidence, whether directly stated or logically inferable. Pay attention to potential ambiguities in the query sentence. Evaluate based solely on the information present within the query sentence; external information, including the provided support sentence, is irrelevant. Treat the support sentence as an example for context only; completely disregard it when making your judgment. Respond with a clear '"'"'yes'"'"' or '"'"'no'"'"' to indicate whether the relation is confirmed, considering only the query sentence.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_evoprompt_node_x_greater-tg --prompt 'You will be provided with a relation name, a detailed description of the relation, a support sentence to illustrate the relation'"'"'s core characteristics, and a query sentence. Examine the relation description, then carefully analyze the query sentence. The Subject and Object are clearly identified. First, identify the tagged Subject and Object. Then, verify the consistency between the relation'"'"'s definition, the entities'"'"' semantic roles from the intended direction, and the presence of supporting evidence, whether directly stated or logically inferable. Pay attention to potential ambiguities in the query sentence. Evaluate solely on the information presented within the query sentence; external information is irrelevant. Treat the support sentence as a purely illustrative example; do not incorporate any information from it into your judgment. Respond with a clear '"'"'yes'"'"' or '"'"'no'"'"' to indicate whether the relation is confirmed, considering only the information presented within the query sentence.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_evoprompt_node_x_gradpo-prob --prompt 'You will be provided with a relation name, a detailed description of the relation, a support sentence to illustrate the relation’s core characteristics, and a query sentence. Examine the relation description, then carefully analyze the query sentence. The Subject and Object are clearly identified. First, identify the tagged Subject and Object. Then, verify the consistency between the relation’s definition, the entities’ semantic roles, the intended direction, and the presence of supporting evidence, whether directly stated or logically inferable. Pay attention to potential ambiguities in the query sentence. Evaluate solely on the informational presented within the query sentence; external information is irrelevant. Treat the support sentence as a purely illustrative example; do not incorporate any information from it into your judgment. Respond with a clear '"'"'yes'"'"' or '"'"'no'"'"' to indicate whether the relation is confirmed, considering only the informational presented within the query sentence.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_evoprompt_node_y --prompt 'You are given a relation name, its description in brackets [relation description], a support sentence exemplifying the relation, and a query sentence. First, understand the relation description. Then, consider the query sentence. The Subject and Object are already identified by tags. Read the relation description, then read the query sentence. Carefully review the relation definition. Carefully analyze the relation description, then thoroughly evaluate the query sentence. First identify the tagged Subject and Object, then compare their roles to the relation name and definition. Confirm that the relation direction is Subject-to-Object, and that the relation is demonstrable within the query sentence. Verify the consistency of entity types, roles, and directional flow. Rely exclusively on the query sentence for verification and assess its explicitness. The support sentence illustrates the relation type; evidence must originate solely from the query. Determine if the relation holds for the query sentence. Provide a direct '"'"'yes'"'"' or '"'"'no'"'"' answer, based solely on the information presented in the query sentence.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_evoprompt_node_y_lpo --prompt 'You are given a relation name, its description in brackets [relation description], a support sentence exemplifying the relation, and a query sentence. Understand the relation description. Then, consider the query sentence. The Subject and Object are already identified by tags. Read the relation description, then read the query sentence. Focus on the relation definition. Carefully analyze the relation description, then thoroughly evaluate the query sentence. First identify the tagged Subject and Object, then compare their roles to the relation name and definition. Confirm that the relation direction is Subject-to-Object, and that the relation is demonstrable within the query sentence. Verify the consistency of entity types, roles, and directional flow. Prioritize the query sentence for verification, ensuring the relation is explicitly stated or directly implied within it. The support sentence illustrates the relation type; evidence must originate solely from the query. Determine if the relation holds for the query sentence. Provide a direct '"'"'yes'"'"' or '"'"'no'"'"' answer, based solely on the information presented in the query sentence. Omit external knowledge. Respond with '"'"'yes'"'"' or '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_evoprompt_node_y_greater --prompt 'This are given a relation name, its description in brackets [relation description], a support sentence exemplifying the relation, and a query sentence. First, understand the relation description. Then, consider the query sentence. The Subject and Object are already identified by tags. Read the relation description, then read the query sentence. Carefully review the relation definition. Carefully analyze the relation description, then thoroughly evaluate the query sentence. First identify the tagged Subject and Object, then compare their roles to the relation name and definition. Confirm that the relation direction is Subject-to-Object, and that the relation is demonstrable within the query sentence. Verify the consistency of entity types, roles, and directional flow. Rely exclusively on the query sentence for verification and assess its explicitness. The support sentence illustrates the relation type; evidence must originate solely from the query. Determine if the relation holds for the query sentence. Provide a direct '"'"'yes'"'"' or '"'"'no'"'"' answer, based solely on the information presented in the query sentence.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_evoprompt_node_y_greater-tg --prompt 'You are given a relation name, its description in brackets [relation description], a support sentence exemplifying the relation, and a query sentence. First, understand the relation description. Then, consider the query sentence. The Subject and Object are already identified by tags. Read the relation description, then read the query sentence. Carefully review the relation definition. Carefully analyze the relation description, then thoroughly evaluate the query sentence. First identify the tagged Subject and Object, then compare their roles to the relation name and definition. Confirm that the relation direction is Subject-to-Object, and that the relation is demonstrable within the query sentence. Verify the consistency of entity types, roles, and directional flow. Rely exclusively on the query sentence for verification and assess its explicitness. The support sentence illustrates the relation type; evidence must originate solely from the query. Determine if the relation holds for the query sentence. Provide a direct '"'"'yes" or '"'"'no'"'"' answer, based solely on the information presented in the query sentence.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_evoprompt_node_y_gradpo-gen --prompt 'You are given a relation name, its description in brackets [relation description], a support sentence that exemplifies the relation, and a query sentence. First, understand the relation description. Then, consider the query sentence. The Subject and Object are already identified by tags. Read the relation description, then read the query sentence. Carefully review the relation definition. Carefully analyze the relation description, then thoroughly evaluate the query sentence. First identify the tagged Subject and Object, then compare their roles to the relation name and definition. Confirm that the relation direction is Subject-to-Object, and that the relation is demonstrable within the query sentence. Verify the consistency of entity types, roles, and directional flow. Rely exclusively on the query sentence for verification and assess its explicitnessness. The support sentence exemplifies the relation type; evidence must originate solely from the query. Determine if the relation holds for the query sentence. Provide a direct '"'"'yes'"'"' or '"'"'no'"'"' answer, based solely on the information presented in the query sentence.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_evoprompt_node_y_gradpo-prob --prompt 'You are given a relation name, its description in brackets [relation description], a support sentence exemplifying the relation, and a query sentence. First, understand the relation description. Then, consider the query sentence. The Subject and Object are already identified by tags. Read the relation description, then read the query sentence. Carefully review the relation definition. Carefully analyze the relation description, then thoroughly evaluate the query sentence. First identify the tagged Subject and Object, then compare their roles to the relation name and definition. Confirm that the relation direction is Subject-to-Object, and that the relation is demonstrable within the query sentence. Verify the consistency of entity types, roles, and directional flow. Rely exclusively on the query sentence for verification and assess its expliciteness. The support sentence illustrates the relation type; evidence must originate solely from the query. Determine if the relation holds for the query sentence. Provide a direct '"'"'yes'"'"' or '"'"'no'"'"' answer, based solely on the information presented in the query sentence.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_etgpo_node_x --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively.

Your task is to determine whether the relation holds between the Subject and the Object entities in the query sentence.  Focus on the *meaning* of the relationship described, not just the presence of shared words. Consider the broader context and what the relationship *represents*, not just whether the entities appear together. 

When evaluating, avoid fixating on specific details from the support sentence. Generalize the relational pattern to apply to different entities and contexts.  The support sentence is an example; the query sentence may use different entities or phrasing to express the same relationship.

Be mindful of nuances in meaning. The relation type describes a specific connection; do not infer the relationship unless it is clearly and directly present in the query sentence, even if related concepts are mentioned.  Focus on the *core* of the relation.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_etgpo_node_x_lpo --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively.

Your task is to determine if the query sentence *explicitly and directly* expresses the relationship described by the relation name and exemplified in the support sentence, between the Subject and the Object entities.  Prioritize a clear, demonstrable connection over subtle or implied relationships. Focus on the *essential* meaning of the relationship, rather than just shared words. Consider the broader context, but primarily assess whether the query sentence *states* the relationship.

Do not fixating on specific details from the support sentence. Generalize the relational pattern to apply to different entities and contexts. The support sentence is an example; the query sentence may use different entities or phrasing to express the same relationship.

Be mindful of nuances in meaning. The relation type describes a specific connection; do not infer the relationship unless it is clearly and directly present in the query sentence, even if related concepts are mentioned. Focus on the *core* of the relation.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_etgpo_node_x_gradpo-gen --prompt 'You are given a relation category, a description of the relation in brackets, a demonstration of the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively.

Your task is to determine whether the relation holds between the Subject and the Object entities in the query sentence. Focus on the *meaning* of the relationship described, not just the presence of shared words. Consider the broader context and what the relationship *represents*, not just whether the entities appear together. 

When evaluating, avoid fixating on specific details from the demonstration of sentence. Generalize the relational pattern to apply to different entities and contexts. The demonstration of sentence is an example; the query sentence may use different entities or phrasing to express the same relationship.

Be mindful of nuances in meaning. The relation category describes a specific connection; do not infer the relationship unless it is clearly and directly present in the query sentence, even if related concepts are mentioned. Focus on the *core* of the relation.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_rpo_node_x --prompt 'You are given a relation name, a description of the relation in brackets, a support instance that exemplifies the relation, and a query sentence. The relation connects a **subject entity** and an **object entity**, which are marked with the <subject> and <object> tags, respectively. Your task is to determine whether the relation described in the support instance holds between the subject and object entities in the query sentence. 

**Key Steps:**
1. **Identify the subject and object entities** in the query sentence (they are marked with <subject> and <object> tags).
2. **Analyze the relation** based on the provided description and the support instance. The relation must be a direct, specific connection between the subject and object entities as defined in the description.
3. **Check the query sentence** for explicit evidence of the relation. If the subject and object entities in the query are not connected by the relation described (e.g., the object is not the correct entity type, or the connection is not explicitly stated), answer "no."

**Example:**  
For the relation "director," the subject (e.g., a film) must be connected to the object (e.g., a person) through the relation described in the support instance. If the object in the query is a genre or a different entity type, the answer is "no."

If the relation holds between the subject and object entities in the query sentence, answer "yes"; otherwise, answer "no."'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_rpo_node_x_lpo --prompt 'You are given a relation name, a description of the relation in brackets, a support instance that exemplifies the relation, and a query sentence. The relation connects a **subject entity** and an **object entity**, which are marked with the <subject> and <object> tags, respectively. Your task is to determine whether the relation described in the support instance holds between the subject and object entities in the query sentence. 

**Key Steps:**
1. **Identify the subject and object entities** in the query sentence (they are marked with <subject> and <object> tags).
2. **Analyze the relation** based on the provided description and the support instance. The relation must be a direct, specific connection from the subject to the object in the same direction as the support instance as defined in the description and the direction of the relation (subject to object) must match exactly.
3. **Check the query sentence** for explicit evidence of the relation. If the subject and object entities in the query are not connected by the relation described (e.g., entity types of both the subject and object must match those in the support instance or the connection is not explicitly stated), answer "no."

**Example:**  
For the relation "director," the subject (e.g., a film) must be connected to the object (e.g., a person) through the relation described in the support instance. If the object in the query is a genre or a different entity type, the answer is "no."

If the relation holds between the subject and object entities in the query sentence, answer "yes"; otherwise, answer "no."'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:1 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_rpo_node_x_greater --prompt 'To are given a relation name, a description of the relation in brackets, a support instance that exemplifies the relation, and a query sentence. The relation connects a **subject entity** and an **object entity**, which are marked with the <subject> and <object> tags, respectively. Your task is to determine whether the relation described in the support instance holds between the subject and object entities in the query sentence. 

**Key Steps:**
1. **Identify the subject and object entities** in the query sentence (they are marked with <subject> and <object> tags).
2. **Analyze the relation** based on the provided description and the support instance. The relation must be a direct, specific connection between the subject and object entities as defined in the description.
3. **Check the query sentence** for explicit evidence of the relation. If the subject and object entities in the query are not connected by the relation described (e.g., the object is not the correct entity type, or the connection is not explicitly stated), answer "no."

**Example:**  
For the relation "director," the subject (e.g., a film) must be connected to the object (e.g., a person) through the relation described in the support instance. If the object in the query is a genre or a different entity type, the answer is "no."

If the relation holds between the subject and object entities in the query sentence, answer "yes"; otherwise, answer "no."'
