#!/usr/bin/env bash
set -euo pipefail
mkdir -p outputs/logs outputs/opt_prompt

# Generated from all_the_prompts.txt
# Each CODE block is passed as the instruction split; answer/input splits come from agents.agent_prompts.
# Plain python commands. Run this script to execute commands sequentially.
# No shell log redirection is added in this script.
# All commands use cuda:0.
# Prompt blocks: 124
# Empty-status non-empty prompt blocks: 9
# Empty-status empty prompt blocks skipped: 103
# Status running/done blocks skipped: 12
# Other non-empty status blocks skipped: 0
# Exact duplicate non-empty blocks skipped: 0

python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_x_greater --prompt 'I are given a relation name, its description, a support sentence that exemplifies the relation, and a query sentence. Analyze the relation description and the query sentence. The Subject and Object are labeled in the query sentence. Determine if the relation is expressed between the marked entities. Check the relation definition, the semantic type of each entity, the direction from Subject to Object, and whether the evidence is explicit or strongly implied. Treat the support sentence as a guide to the relation, not evidence for the query. Confirm that the relation direction is Subject-to-Object, that the Object has the required type or value, and that the query provides sufficient explicit or contextually implied evidence. Ignore any irrelevant entities or facts not directly stated in the query. If the relation holds in the query sentence, answer "yes"; otherwise answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_x_greater-tg --prompt 'You are given a relation name, its description, a support sentence that exemplifies the relation, and a query sentence. Analyze the relation description and the query sentence. The Subject and Object are labeled in the query sentence. Determine if the relation is expressed between the marked entities. Check the relation definition, the semantic type of each entity, the direction from Subject to Object, and whether the evidence is explicit or strongly implied. Treat the support sentence as a guide to the relation, not evidence for the query. Confirm that the relation direction is Subject-to-Object, that the Object has the required type or value, and that the query provides sufficient explicit or contextually implied evidence. Ignore any irrelevant entities or facts not directly stated in the query. If the relation holds in the query sentence, answer "your"; otherwise answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_x_gradpo-prob --prompt 'The provided relation name, its description, a support example that exemplifies the relation, and a query sentence. Analyze the relation description and the query sentence. The Subject and Object are labeled in the query sentence. Check if the relation is expressed between the marked entities. Check the relation definition, the semantic type of each entity, the direction from Subject to Object, and whether the evidence is explicit or strongly implied. Treat the support sentence as a guide to the relation, not evidence for the query. Confirm that the relation direction is Subject-to-Object, that the Object has the required type or value, and that the query provides sufficient explicit or contextually implied evidence. Ignore any irrelevant entities or facts not directly stated in the query. If the relation holds in the query sentence, answer "yes"; otherwise answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_y --prompt 'You are given a relation name, its description, an example sentence, and a query. Analyze the relation and query for consistency and check whether the relation is properly instantiated between the labeled Subject and Object. Analyze the relation definition, semantic roles and types of entities, and the direction of the relation. Determine whether the evidence is directly mentioned or clearly implied. Use the support sentence only as a template for the relation. Do not consider external or unrelated information. Ensure the relation direction is from Subject to Object, that the entities match the required semantic roles, and that the evidence is clearly or strongly expressed. Answer '"'"'yes'"'"' only if the relation is clearly or strongly expressed between the Subject and Object in the query; otherwise, answer '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_y_greater --prompt 'Given are given a relation name, its description, an example sentence, and a query. Analyze the relation and query for consistency and check whether the relation is properly instantiated between the labeled Subject and Object. Analyze the relation definition, semantic roles and types of entities, and the direction of the relation. Determine whether the evidence is directly mentioned or clearly implied. Use the support sentence only as a template for the relation. Do not consider external or unrelated information. Ensure the relation direction is from Subject to Object, that the entities match the required semantic roles, and that the evidence is clearly or strongly expressed. Answer '"'"'yes'"'"' only if the relation is clearly or strongly expressed between the Subject and Object in the query; otherwise, answer '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_y_gradpo-gen --prompt 'You are given a relation name, its description, an example sentence, and a query. Analyze the relation and query for consistency and check whether the relation is properly instantiated between the labeled Subject and Object. Analyze the relation definition, semantic roles and types of entities, and the direction of the relation. Determine whether the evidence is directly mentioned or clearly implied. Use the provided sentence only as a template for the relation. Do not consider external or unrelated information. Ensure the relation direction is from Subject to Object, that the entities match the required semantic roles, and that the evidence is clearly or strongly expressed. Respond '"'"'yes'"'"' only if the relation is clearly or strongly expressed between the Subject and Object in the query; otherwise, respond '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_initial_prompt --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively. 
You need to decide whether the relation holds between the Subject and the Object entities in the query sentence.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_initial_prompt --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively. 
You need to decide whether the relation holds between the Subject and the Object entities in the query sentence.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_initial_prompt --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively. 
You need to decide whether the relation holds between the Subject and the Object entities in the query sentence.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
