python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_rpo_node_x_gradpo-gen --prompt 'You are told a relation name, a description of the relation in quotes, a support instance that exemplifies the relation, and a query text. The relation connects a **subject entity** and an **object entity**, which are marked with the <subject> and <object> tags, respectively. Your task is to determine whether the relation described in the support instance holds between the subject and object entities in the query text. 

**Key Steps:**
1. **Identify the subject and object entities** in the query text (they are marked with <subject> and <object> tags).
2. **Analyze the relation** based on the provided description and the support instance. The relation must be a direct, specific connection between the subject and object entities as defined in the description.
3. **Check the query text** for explicit evidence of the relation. If the subject and object entities in the query are not connected by the relation described (e.g., the object is not the correct entity type, or the connection is not explicitly stated), answer "no."

**Example:**  
For the relation "director," the subject (e.g., a film) must be connected to the object (e.g., a person) through the relation described in the support instance. If the object in the query is a genre or a different entity type, the answer is "no."

If the relation holds between the subject and object entities in the query text, answer "yes"; otherwise, answer "no."'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 8 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_rpo_node_y --prompt 'You are given a relation name, a description of the relation in brackets, a support instance illustrating the relation, and a query sentence. The relation connects a **subject** entity (marked with <subject> tags) and an **object** entity (marked with <object> tags). Your task is to determine whether the query sentence explicitly expresses the relation defined by the relation name and description.

**Key Guidelines:**
1. **Understand the relation'"'"'s definition precisely**: 
   - For "original network", the subject (e.g., a program or show) must be explicitly tied to the object (e.g., a TV network or platform) as its original distribution channel. This includes direct mentions of the network or platform in the sentence.
   - For "residence", the subject (e.g., a person or entity) must be explicitly tied to the object (e.g., a location) as a place they live or are associated with.
   - For "instance of", the subject must be explicitly described as a specific example of the object (e.g., a song being part of an album, a dam being a type of structure). This requires a direct part-whole or category relationship, not a location-based or functional one.

2. **Focus on the subject and object tags**: Identify the subject and object entities in the query sentence as per the tags. Ensure you do not confuse the subject with a role or the object with a location unless explicitly defined by the relation. For example, "BBC Three" in the "original network" relation is a network entity, not a location.

3. **Avoid conflating association with location or function**: 
   - "Original network" requires a direct link between the subject (e.g., a show) and the object (e.g., a network) as its original platform.
   - "Residence" requires a location-based connection (e.g., a person living in a city).
   - "Instance of" requires a part-whole or category relationship (e.g., a song being part of an album, a dam being a type of structure), not a location or functional relationship.

4. **Check for explicitness**: The relation must be explicitly stated or implied by the sentence'"'"'s structure. For example, "Schatz was inaugurated as Hawaii'"'"'s lieutenant governor" explicitly links the role (subject) to the jurisdiction (object), satisfying "applies to jurisdiction." Similarly, "The Smoking Room" (subject) is explicitly tied to "BBC Three" (object) as a sitcom aired on that network, satisfying "original network."

**Example Clarification**: 
- In the "original network" relation, the object must be a network or platform (e.g., "BBC Three", "Canal 13") that directly distributes the subject'"'"'s work. 
- In the "instance of" relation, the subject must be a specific example of the object (e.g., a song on an album, a dam in a country), not a location or category.

Answer "yes" if the query sentence explicitly expresses the relation as defined; otherwise, answer "no."'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 8 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_rpo_node_y_greater-tg --prompt 'You are given a relation name, a description of the relation in brackets, a support instance illustrating the relation, and a query sentence. The relation connects a **subject** entity (marked with <subject> tags) and an **object** entity (marked with <object> tags). Your task is to determine whether the query sentence explicitly expresses the relation defined by the relation name and description.

**Key Guidelines:**
1. **Understand the relation'"'"'s definition precisely**: 
   - For "original network", the subject (e.g., a program or show) must be explicitly tied to the object (e.g., a TV network or platform) as its original distribution channel. This includes direct mentions of the network or platform in the sentence.
   - For "residence", the subject (e.g., a person or entity) must be explicitly tied to the object (e.g., a location) as a place they live or are associated with.
   - For "instance of", the subject must be explicitly described as a specific example of the object (e.g., a song being part of an album, a dam being a type of structure). This requires a direct part-whole or category relationship, not a location-based or functional one.

2. **Focus on the subject and object tags**: Identify the subject and object entities in the query sentence as per the tags. Ensure you do not confuse the subject with a role or the object with a location unless explicitly defined by the relation. For example, "BBC Three" in the "original network" relation is a network entity, not a location.

3. **Avoid conflating association with location or function**: 
   - "Original network" requires a direct link between the subject (e.g., a show) and the object (e.g., a network) as its original platform.
   - "Residence" requires a location-based connection (e.g., a person living in a city).
   - "Instance of" requires a part-whole or category relationship (e.g., a song being part of an album, a dam being a type of structure), not a location or functional relationship.

4. **Check for explicitness**: The relation must be explicitly stated or implied by the sentence'"'"'s structure. For example, "Schatz was inaugurated as Hawaii'"'"'s lieutenant governor" explicitly links the role (subject) to the jurisdiction (object), satisfying "applies to jurisdiction." Similarly, "The Smoking Room" (subject) is explicitly tied to "BBC Three" (object) as a sitcom aired on that network, satisfying "original network."

**Example Clarification**: 
- In the "original network" relation, the object must be a network or platform (e.g., "BBC Three", "Canal 13") that directly distributes the subject'"'"'s work. 
- In the "instance of" relation, the subject must be a specific example of the object (e.g., a song on an album, a dam in a country), not a location or category.

 Do "yes" if the query sentence explicitly expresses the relation as defined; otherwise, answer "no."'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 8 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_rpo_node_y_gradpo-gen --prompt 'You are given a relation label, a description of the relation in curly braces, a support occurrence illustrating the relation, and a query sentence. The relation connects a **subject** entity (marked with <subject> tags) and an **object** entity (marked with <object> tags). Your task is to determine whether the query sentence clearly indicates the relation defined by the relation label and description.

**Key Guidelines:**
1. **Understand the relation'"'"'s definition precisely**: 
   - For "original network", the subject (e.g., a program or show) must be explicitly tied to the object (e.g., a TV network or platform) as its original distribution channel. This includes direct mentions of the network or platform in the sentence.
   - For "residence", the subject (e.g., a person or entity) must be explicitly tied to the object (e.g., a location) as a place they live or are associated with.
   - For "instance of", the subject must be explicitly described as a specific example of the object (e.g., a song being part of an album, a dam being a type of structure). This requires a direct part-whole or category relationship, not a location-based or functional one.

2. **Focus on the subject and object tags**: Identify the subject and object entities in the query sentence as per the tags. Ensure you do not confuse the subject with a role or the object with a location unless explicitly defined by the relation. For example, "BBC Three" in the "original network" relation is a network entity, not a location.

3. **Avoid conflating association with location or function**: 
   - "Original network" requires a direct link between the subject (e.g., a show) and the object (e.g., a network) as its original platform.
   - "Residence" requires a location-based connection (e.g., a person living in a city).
   - "Instance of" requires a part-whole or category relationship (e.g., a song being part of an album, a dam being a type of structure), not a location or functional relationship.

4. **Check for explicitness**: The relation must be explicitly stated or implied by the sentence'"'"'s structure. For example, "Schatz was inaugurated as Hawaii'"'"'s lieutenant governor" explicitly links the role (subject) to the jurisdiction (object), satisfying "applies to jurisdiction." Similarly, "The Smoking Room" (subject) is explicitly tied to "BBC Three" (object) as a sitcom aired on that network, satisfying "original network."

**Example Clarification**: 
- In the "original network" relation, the object must be a network or platform (e.g., "BBC Three", "Canal 13") that directly distributes the subject'"'"'s work. 
- In the "instance of" relation, the subject must be a specific example of the object (e.g., a song on an album, a dam in a country), not a location or category.

Answer "yes" if the query sentence clearly indicates the relation as defined; otherwise, answer "no."'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 8 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_rpo_node_y_gradpo-prob --prompt 'You are given a relation name, a description of the relation in [brackets], a support example instance illustrating the relation, and a query sentence. The relation connects a **subject** entity (marked with <subject> tags) and an **object** entity (marked with <object> tags). Your task is to determine whether the query sentence explicitly expresses the relation defined by the relation name and description.

**Key Guidelines:**
1. **Understand the relation'"'"'s definition precisely**: 
   - For "original network", the subject (e.g., a program or show) must be explicitly tied to the object (e.g., a TV network or platform) as its original distribution channel. This includes direct mentions of the network or platform in the sentence.
   - For "residence", the subject (e.g., a person or entity) must be explicitly tied to the object (e.g., a location) as a place they live or are associated with.
   - For "instance of", the subject must be explicitly described as a specific example of the object (e.g., a song being part of an album, a dam being a type of structure). This requires a direct part-whole or category relationship, not a location-based or functional one.

2. **Focus on the subject and object tags**: Identify the subject and object entities in the query sentence as per the tags. Ensure you do not confuse the subject with a role or the object with a location unless explicitly defined by the relation. For example, "BBC Three" in the "original network" relation is a network entity, not a location.

3. **Avoid conflating association with location or function**: 
   - "Original network" requires a direct link between the subject (e.g., a show) and the object (e.g., a network) as its original platform.
   - "Residence" requires a location-based connection (e.g., a person living in a city).
   - "Instance of" requires a part-whole or category relationship (e.g., a song being part of an album, a dam being a type of structure), not a location or functional relationship.

4. **Check for explicitness**: The relation must be explicitly stated or implied by the sentence'"'"'s structure. For example, "Schatz was inaugurated as Hawaii'"'"'s lieutenant governor" explicitly links the role (subject) to the jurisdiction (object), satisfying "applies to jurisdiction." Similarly, "The Smoking Room" (subject) is explicitly tied to "BBC Three" (object) as a sitcom aired on that network, satisfying "original network."

**Example Clarification**: 
- In the "original network" relation, the object must be a network or platform (e.g., "BBC Three", "Canal 13") that directly distributes the subject'"'"'s work. 
- In the "instance of" relation, the subject must be a specific example of the object (e.g., a song on an album, a dam in a country), not a location or category.

Answer "yes" if the query sentence explicitly expresses the relation as defined; otherwise, answer "no."'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_evoprompt_node_x --prompt 'You are given a relation name, its description, a support sentence that illustrates the relation, and a query sentence. Decide whether the specified relation is valid between the marked Subject and Object entities in the query sentence. Check the relation definition, the semantic type of each entity, the direction from Subject to Object, and whether the relation is explicitly or clearly implied in the query. Use the support sentence to clarify the relation’s structure, not to infer new information or transfer facts beyond its model. Respond '"'"'yes'"'"' if the relation is explicitly or clearly implied in the query; otherwise respond '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_evoprompt_node_x_lpo --prompt 'You are given a relation name, its description, a support sentence that illustrates the relation, and a query sentence. Decide whether the specified relation is valid between the marked Subject and Object entities in the query sentence. Check the relation definition, the semantic type of each entity and ensure they match the semantic types in the support sentence, the direction from Subject to Object as defined in the support sentence, and whether the relation is explicitly or clearly implied in the query through explicit mention or contextual clues. Use the support sentence to clarify the relation’s structure, not to infer new information or transfer facts beyond its model. Respond '"'"'yes'"'"' if the relation is explicitly or clearly implied in the query or contextually implied; otherwise respond '"'"'no'"'"'. Align the query'"'"'s entities with the support sentence'"'"'s entity roles.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_evoprompt_node_x_greater --prompt 'Use are given a relation name, its description, a support sentence that illustrates the relation, and a query sentence. Decide whether the specified relation is valid between the marked Subject and Object entities in the query sentence. Check the relation definition, the semantic type of each entity, the direction from Subject to Object, and whether the relation is explicitly or clearly implied in the query. Use the support sentence to clarify the relation’s structure, not to infer new information or transfer facts beyond its model. Respond '"'"'yes'"'"' if the relation is explicitly or clearly implied in the query; otherwise respond '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_evoprompt_node_x_greater-tg --prompt 'You are given a relation name, its description, a support sentence that illustrates the relation, and a query sentence. Read whether the specified relation is valid between the marked Subject and Object entities in the query sentence. Check the relation definition, the semantic type of each entity, the direction from Subject to Object, and whether the relation is explicitly or clearly implied in the query. Use the support sentence to clarify the relation’s structure, not to infer new information or transfer facts beyond its model. Respond '"'"'yes'"'"' if the relation is explicitly or clearly implied in the query; otherwise respond '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_evoprompt_node_x_gradpo-prob --prompt 'You are given a relation name, its description, a support sentence that illustrates the relation, and a query sentence. Determine whether the relation is valid between the subject entities in the query sentence. Check the relation definition, the semantic type of each entity, the direction from Subject to Object, and whether the relation is explicitly or clearly implied in the query. Use the support sentence to clarify the relation’s structure, not to infer new information or transfer facts beyond its model. Respond '"'"'yes'"'"' if the relation is explicitly or clearly implied in the query; otherwise respond '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_etgpo_node_x --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and the Object entities, indicated with the subject and object tags. You need to decide whether the relation holds between the Subject and the Object entities in the query sentence, following these guidelines: (1) Prioritize explicit mentions of the relation in the query sentence over indirect inferences. (2) Strictly adhere to the subject and object tags provided; do not infer or swap their roles. (3) Distinguish between relationship types (e.g., '"'"'designed by'"'"' vs. '"'"'owned by'"'"') based on their definitions, not superficial similarities. (4) Verify that the subject and object match the required entity types for the relation (e.g., a place vs. a character). (5) Avoid conflating part-whole hierarchies (e.g., '"'"'has part'"'"') with product-owner relationships (e.g., '"'"'produced by'"'"'). If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_etgpo_node_x_greater --prompt 'Based are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and the Object entities, indicated with the subject and object tags. You need to decide whether the relation holds between the Subject and the Object entities in the query sentence, following these guidelines: (1) Prioritize explicit mentions of the relation in the query sentence over indirect inferences. (2) Strictly adhere to the subject and object tags provided; do not infer or swap their roles. (3) Distinguish between relationship types (e.g., '"'"'designed by'"'"' vs. '"'"'owned by'"'"') based on their definitions, not superficial similarities. (4) Verify that the subject and object match the required entity types for the relation (e.g., a place vs. a character). (5) Avoid conflating part-whole hierarchies (e.g., '"'"'has part'"'"') with product-owner relationships (e.g., '"'"'produced by'"'"'). If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_etgpo_node_x_gradpo-gen --prompt 'You are given a relation name, a description of the relation in curly brackets, a support example of the relation, and a query sentence. A relation connects the Subject and the Object entities, indicated with the subject and object tags. You need to decide whether the relation holds between the Subject and the Object entities in the query sentence, following these guidelines: (1) Prioritize explicit mentions of the relation in the query sentence over indirect inferences. (2) Strictly adhere to the subject and object tags provided; do not infer or swap their roles. (3) Distinguish between relationship types (e.g., '"'"'designed by'"'"' vs. '"'"'owned by'"'"') based on their definitions, not superficial similarities. (4) Verify that the subject and object match the required entity types for the relation (e.g., a place vs. a character). (5) Avoid conflating part-whole hierarchical hierarchies (e.g., '"'"'has part'"'"') with product-owner relationships (e.g., '"'"'produced by'"'"'). If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_etgpo_node_x_gradpo-prob --prompt 'You are given a relation name, a description of the relation in brackets, a support example exemplifying the relation, and a query sentence. A relation connects the Subject and the Object entities, indicated with the subject and object tags. You need to decide whether the relation holds between the Subject and the Object entities in the query sentence, following these guidelines: (1) Prioritize explicit mentions of the relation in the query sentence over indirect inferences. (2) Strictly adhere to the subject and object tags provided; do not infer or swap their roles. (3) Distinguish between relationship types (e.g., '"'"'designed by'"'"' vs. '"'"'owned by'"'"') based on their definitions, not superficial similarities. (4) Verify that the subject and object match the required entity types for the relation (e.g., a place vs. a character). (5) Avoid conflating part-whole hierarchies (e.g., '"'"'has part'"'"') with product-owner relationships (e.g., '"'"'produced by'"'"'). If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_rpo_node_x --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively. These are entities – consider their types and roles within the sentence. The prompt provides a description of the relation – use this in conjunction with the support instance to guide your reasoning.

You need to decide whether the relation holds between the Subject and the Object entities in the query sentence. The relation may be explicitly stated or implied through the context of the sentence. Carefully consider the surrounding words and phrases to determine if a connection exists.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:2 --ep_start 0 --ep_end 150000 --batch_size 8 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_rpo_node_x_lpo --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. Carefully analyze both sentences, focusing on how the subject and object relate within each. Consider the description of the relation provided – does the query sentence express a similar connection between the subject and object?

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively. These are entities – consider their types and roles within the sentence. The prompt provides a description of the relation – use this in conjunction with the support instance to guide your reasoning.

You need to decide whether the relation holds between the Subject and the Object entities in the query sentence. The relation may be explicitly stated or implied through the context of the sentence. Carefully consider the surrounding words and phrases to determine if a connection exists. Prioritize the explicit expression of the relation, but also consider how the context supports a similar relationship as demonstrated in the support sentence.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no". Your answer must be exactly one token: "yes" or "no".

Example 1 [fn]: gold=yes, prediction=no
Relation: work location ()
Support Sentence: Early in his career , <object>Baton Rouge</object> - area State Representative <subject>Donald Ray Kennard</subject> was an Istrouma faculty member and coach .
Query Sentence: The video ( directed Gil Green ) was shot in <object>Miami</object> , and features cameos by <subject>Rick Ross</subject> , J. R. Rotem , DJ Khaled and Gunplay .

Example 2 [fp]: gold=no, prediction=yes
Relation: headquarters location ()
Support Sentence: John Stadtmiller , who runs <subject>Republic Broadcasting Network</subject> in <object>Round Rock , Texas</object> , which broadcast Sam Kennedy '"'"'s weekly show , said that Kennedy was behind the idea of sending out the letters .
Query Sentence: Feldman has served as president of the Beth Emeth Bais Yehuda Synagogue and of the Ontario Region of the <subject>United Synagogue of America</subject> , the central organization of synagogues in <object>Conservative Judaism</object> .

Example 3 [fn]: gold=yes, prediction=no
Relation: position held ()
Support Sentence: With an elevation of above sea level , it is the third highest mountain in Tasmania and named after <subject>William Giblin</subject> , a previous <object>Premier of Tasmania</object> . W.V.
Query Sentence: Meanwhile , 1868 Democratic nominee and former <object>New York Governor</object> <subject>Horatio Seymour</subject> declined to run again .'
