python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_rpo_node_x_lpo --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and Object entities, which are indicated with the subject and object tags, respectively. 

To determine if the relation holds between the Subject and Object entities in the query sentence, strictly follow these steps:
1. **Verify the subject and object types**: 
   - For relations starting with "org:", the **subject must be an organization** (not a person or role). 
   - For per: relations, the subject must be a person.
   - The **object must align with the relation'"'"'s definition** (e.g., "org:subsidiaries" requires a subsidiary entity, not a role or category; "org:political/religious_affiliation" accepts a religious or political category, not a person). 
2. **Check the relationship**: Confirm that the query sentence explicitly states the link between the Subject and Object as per the relation'"'"'s description, using direct assertions (e.g., "is from," "was born in," "works for") rather than indirect or implied connections. 
3. **Recognize object types**: 
   - The object can be a **specific entity** (e.g., "US-based Ryder Public Transportation Services") or a **explicitly permitted category (e.g., '"'"'Christian,'"'"' '"'"'Islamist,'"'"' '"'"'Lakota'"'"') if the relation explicitly allows it, but avoid treating nationalities, tribes, or administrative regions as valid objects unless explicitly permitted.** 
   - Avoid treating abstract terms (e.g., "Christian") as roles or people unless the relation'"'"'s description explicitly permits it. 
4. **Focus on explicit connections**: Only answer "yes" if the query sentence directly establishes the relation between the subject and object as defined. For example, "org:number_of_employees/members" requires a numerical value (e.g., "42,000") to indicate the count, not a vague term like "many." 

If the relation holds, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_rpo_node_y_lpo --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and Object entities, which are indicated with the subject and object tags, respectively. 

To determine if the relation holds between the Subject and Object entities in the query sentence, strictly follow these steps:
1. **Verify the subject and object types**: The subject must be the entity type expected by the relation (e.g., "org" for organization, "per" for person). The object must match the relation'"'"'s definition (e.g., "org:stateorprovince_of_headquarters" requires the object to be a state/province, not a city or location). must be a state/province and not a city. If the subject is a location (e.g., "Kennedy Space Center"), it must be explicitly tied to an organization (e.g., NASA) as its headquarters. 
2. **Check the relationship**: Confirm that the query sentence explicitly links the Subject and Object as per the relation'"'"'s description. Ensure the query sentence explicitly states the relation between the subject and object as per the relation'"'"'s description (e.g., "state/province" for headquarters, "family member" for other_family). For example, "org:stateorprovince_of_headquarters" requires the subject to be an organization (e.g., "NASA") and the object to be a state/province (e.g., "Florida"), not a location (e.g., "Kennedy Space Center"). For "org:political/religious_affiliation," the object must be the organization'"'"'s actual political or religious affiliation (e.g., "Islamist"), not a role, descriptor, or faction. 
3. **Avoid role vs. person confusion**: If the object is a role (e.g., "chief executive") or title (e.g., "Rep."), it does not satisfy relations requiring a person (e.g., "employee_of"). Possessive pronouns (e.g., "his", "her") do not satisfy relations requiring a person (e.g., "other_family"). Similarly, ensure the subject is the correct entity type (e.g., "org" for organizations, "per" for people). For "org:stateorprovince_of_headquarters," the subject must be an organization (e.g., "NASA"), not a location (e.g., "Kennedy Space Center"), unless the sentence explicitly states the location is the organization'"'"'s headquarters. 
4. **Focus on explicit connections**: Only answer "yes" if the query sentence directly establishes the relation between the subject and object as defined. This includes ensuring the object is the correct entity type (e.g., "state/province" for headquarters, "political/religious affiliation" for org:political/religious_affiliation) and that the subject is the correct entity type for the relation. 

If the relation holds, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_y_lpo --prompt 'You are given a relation name, its description, an example sentence, and a query. Analyze the relation and query for consistency and check whether the relation is clearly instantiated between the labeled Subject and Object. Analyze the relation definition, semantic roles and types of entities, and the direction of the relation. Determine whether the evidence is strongly mentioned or clearly implied. Use the support sentence only as a template for the relation. Do not consider external or unrelated information. Ensure the relation direction is strictly from Subject to Object, that the entities correctly match the required semantic roles, and that the evidence is strongly mentioned or strongly expressed. Answer '"'"'yes'"'"' only if the relation is explicitly mentioned or strongly expressed between the Subject and Object in the query; otherwise, answer '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_etgpo_node_x_lpo --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and the Object entities indicated by subject/object tags. You must determine if the relation holds between the tagged entities in the query sentence, following these rules:

1. **Entity Resolution**: Treat abbreviations (e.g., '"'"'Minn.'"'"') as their full forms (e.g., '"'"'Minnesota'"'"'), and ensure the object matches the required entity type (e.g., state/province vs. city vs. country, URLs). 
2. **Explicit Matching**: Only use information explicitly stated in the query. Do not infer events (e.g., death) or relationships (e.g., familial ties) unless directly mentioned.
3. **Relation Type Precision**: Match the exact relationship type specified (e.g., '"'"'familial'"'"' vs. '"'"'friendship'"'"'). Do not conflate non-familial roles with familial relations. Organizational components such as congresses may imply membership if explicitly named.
4. **Role Implication Awareness**: Recognize that certain roles (e.g., '"'"'managing principal'"'"') inherently imply specific relationships (e.g., '"'"'shareholder'"'"') even if not explicitly stated. Include organizational roles (e.g., '"'"'member'"'"', '"'"'committee'"'"') that directly indicate membership.
5. **Geographic Hierarchy**: Distinguish between sovereign countries (e.g., '"'"'Cuba'"'"') and subnational entities (e.g., '"'"'California'"'"'). A country cannot satisfy a relation requiring a state/province. Subnational entities such as states or provinces are not sovereign. 

Answer '"'"'yes'"'"' if the relation holds under these constraints; otherwise, answer '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_etgpo_node_x_greater --prompt 'Given are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and the Object entities indicated by subject/object tags. You must determine if the relation holds between the tagged entities in the query sentence, following these rules:

1. **Entity Resolution**: Treat abbreviations (e.g., '"'"'Minn.'"'"') as their full forms (e.g., '"'"'Minnesota'"'"'), and ensure the object matches the required entity type (e.g., state/province vs. city vs. country).
2. **Explicit Matching**: Only use information explicitly stated in the query. Do not infer events (e.g., death) or relationships (e.g., familial ties) unless directly mentioned.
3. **Relation Type Precision**: Match the exact relationship type specified (e.g., '"'"'familial'"'"' vs. '"'"'friendship'"'"'). Do not conflate non-familial roles with familial relations.
4. **Role Implication Awareness**: Recognize that certain roles (e.g., '"'"'managing principal'"'"') inherently imply specific relationships (e.g., '"'"'shareholder'"'"') even if not explicitly stated.
5. **Geographic Hierarchy**: Distinguish between sovereign countries (e.g., '"'"'Cuba'"'"') and subnational entities (e.g., '"'"'California'"'"'). A country cannot satisfy a relation requiring a state/province.

Answer '"'"'yes'"'"' if the relation holds under these constraints; otherwise, answer '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_etgpo_node_x_greater-tg --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and the Object entities indicated by subject/object tags. You must determine if the relation holds between the tagged entities in the query sentence, following these rules:

1. **Entity Resolution**: Treat abbreviations (e.g., '"'"'Minn.'"'"') as their full forms (e.g., '"'"'Minnesota'"'"'), and ensure the object matches the required entity type (e.g., state/province vs. city vs. country).
2. **Explicit Matching**: Only use information explicitly stated in the query. Do not infer events (e.g., death) or relationships (e.g., familial ties) unless directly mentioned.
3. **Relation Type Precision**: Match the exact relationship type specified (e.g., '"'"'familial'"'"' vs. '"'"'friendship'"'"'). Do not conflate non-familial roles with familial relations.
4. **Role Implication Awareness**: Recognize that certain roles (e.g., '"'"'managing principal'"'"') inherently imply specific relationships (e.g., '"'"'shareholder'"'"') even if not explicitly stated.
5. **Geographic Hierarchy**: Distinguish between sovereign countries (e.g., '"'"'Cuba'"'"') and subnational entities (e.g., '"'"'California'"'"'). A country cannot satisfy a relation requiring a state/province.

Answer '"'"'none'"'"' if the relation holds under these constraints; otherwise, answer '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_etgpo_node_x_gradpo-gen --prompt 'You are supplied a relation name, a description of the relation in curly brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and the Object entities indicated by subject/object tags. You must determine if the relation holds between the tagged entities in the query sentence, following these rules:

1. **Entity Resolution**: Treat abbreviations (e.g., '"'"'Minn.'"'"') as their full forms (e.g., '"'"'Minnesota'"'"'), and ensure the object matches the required entity type (e.g., state/province vs. city vs. country).
2. **Explicit Matching**: Only use information explicitly stated in the query. Do not infer events (e.g., death) or relationships (e.g., familial ties) unless directly mentioned.
3. **Relation Type Precision**: Match the exact relationship type specified (e.g., '"'"'familial'"'"' vs. '"'"'friendship'"'"'). Do not conflate non-familial roles with familial relations.
4. **Role Implication Awareness**: Recognize that certain roles (e.g., '"'"'managing principal'"'"') inherently imply specific relationships (e.g., '"'"'shareholder'"'"') even if not explicitly stated.
5. **Geographic Hierarchy**: Distinguish between sovereign countries (e.g., '"'"'Cuba'"'"') and subnational entities (e.g., '"'"'California'"'"'). A country cannot satisfy a relation requiring a state/province.

Answer '"'"'yes'"'"' if the relation holds under these constraints; otherwise, answer '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_etgpo_node_x_gradpo-prob --prompt 'Answer the question by determining if the relation holds under these constraints. A relation connects the Subject and the Object entities indicated by subject/object tags. You must determine if the relation holds between the tagged entities in the query sentence, following these rules:

1. **Entity Resolution**: Treat abbreviations (e.g., '"'"'Minn.'"'"') as their full forms (e.g., '"'"'Minnesota'"'"'), and ensure the object matches the required entity type (e.g., state/province vs. city vs. country).
2. **Explicit Matching**: Only use information explicitly stated in the query. Do not infer events (e.g., death) or relationships (e.g., familial ties) unless directly mentioned.
3. **Relation Type Precision**: Match the exact relationship type specified (e.g., '"'"'familial'"'"' vs. '"'"'friendship'"'"'). Do not conflate non-familial roles with familial relations.
4. **Role Implication Awareness**: Recognize that certain roles (e.g., '"'"'managing principal'"'"') inherently imply specific relationships (e.g., '"'"'shareholder'"'"') even if not explicitly stated.
5. **Geographic Hierarchy**: Distinguish between sovereign countries (e.g., '"'"'Cuba'"'"') and subnational entities (e.g., '"'"'California'"'"'). A country cannot satisfy a relation requiring a state/province.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_rpo_node_x_lpo --prompt 'You are given a relation name, a description of the relation in brackets, and a query sentence. Completely disregard any support sentences. Your decision must be based *exclusively* on the information presented within the query sentence and the subject/object tags.

Your task is to determine whether the *specific relation* described holds between the Subject and the Object entities in the *query sentence*. The Subject and the Object entities are indicated with the subject and object tags, respectively. Carefully examine the query sentence, paying close attention to keywords and phrases commonly associated with the specified relation.

Consider the following:

*   **Explicit Statements:** Look for direct statements that express the relation (e.g., "is a subsidiary of," "was born in").
*   **Strong Indicators:** Recognize that relations can be implied or indicated through related language. For example, "native of" often implies "city of birth," and "subsidiary of" directly indicates an organizational relationship.
*   **Contextual Clues:** Evaluate the surrounding context to confirm the relationship.

Do not answer "yes" unless the query sentence explicitly or strongly implies the specified relation. Base your decision *solely* on the content of the query sentence. Do not consider any support examples provided.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_rpo_node_y_greater --prompt 'Relation are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively. Your task is to determine whether the *specific relation* described holds between the Subject and the Object entities in the *query sentence*. Carefully examine the query sentence and consider the relationship between the subject and object entities. Do not answer "yes" simply because the subject and object are related in a general sense; verify that the query sentence explicitly or implicitly expresses the specified relation. Base your decision *solely* on the content of the query sentence. Ignore the support sentence.

When evaluating whether a relation holds, focus on the *core meaning* of the relation. Consider that the query sentence may express the relation using different phrasing or terminology than the relation description. Look for synonyms and related concepts that indicate the presence of the relation. Pay attention to context clues and implied relationships; the relation does not always need to be stated explicitly. Look beyond surface-level phrasing.

Avoid being distracted by surrounding details or circumstantial information within the query sentence that do not directly establish the relation. Prioritize understanding the core relationship between the subject and object, even if it is not stated using the exact words from the relation description. Consider the overall meaning of the sentence, even if the relationship is expressed indirectly.

<b>To help you reason, consider these questions before answering:</b>
* Does the sentence state or strongly imply a connection between the subject and the object that aligns with the relation description?
* Are there keywords or phrases that are closely associated with the relation, even if they are not exact synonyms?
* Could a reasonable person, knowing the relation description, conclude that the subject and object are connected in this way based *only* on the query sentence?
* **Specifically, identify the words or phrases in the query sentence that relate to the subject and object and explain how they suggest the relation. If the relation is not explicitly stated, what is the implied connection?**

<b>Pay close attention to the entities themselves. Are you focusing on the correct entities as the subject and object? Confirm you'"'"'ve correctly identified which entity corresponds to which role.</b>

<b>Be mindful of potential ambiguities. Does the sentence present multiple possible interpretations? If so, choose the interpretation that best supports the relation.</b>

<b>Do not let pronouns or other linguistic complexities obscure the core meaning of the sentence. Focus on the concrete information presented.**

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
