python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_etgpo_node_x --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively.

You need to decide whether the relation holds between the Subject and the Object entities in the query sentence. Focus on the *core meaning* of the relation, not superficial word matches with the support sentence. Consider the broader context of the query sentence and how the relationship might apply even if the specific entities or wording are different.  Recognize that relationships can exist even if the query uses different phrasing or figurative language (e.g., '"'"'like,'"'"' '"'"'similar to'"'"') to express the connection. Adapt your reasoning to the specific context of the query; a relationship that applies to cities might not directly apply to events in the same way. If the query demonstrates the same underlying relationship between the Subject and Object as defined by the relation, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_etgpo_node_x_lpo --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. First, carefully identify what qualities define the Subject and Object within the context of the relation. Then, determine the key properties that characterize the relationship described in the support sentence.  Assess if the query sentence demonstrates these same key properties between the Subject and Object, considering the broader context. A single difference in the relationship'"'"'s properties is sufficient to conclude it does not hold.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively.

You need to decide whether the relation holds between the Subject and the Object entities in the query sentence. Focus on the *core meaning* of the relation, not superficial word matches with the support sentence. Consider the broader context of the query sentence and how the relationship might apply even if the specific entities or wording are different. Recognize that relationships can exist even if the query uses different phrasing or figurative language (e.g., '"'"'like,'"'"' '"'"'similar to'"'"') to express the connection. Ensure your reasoning is grounded in the key properties of the relationship, and remember that a single contrasting property warrants a "no" answer. If the query demonstrates the same underlying relationship between the Subject and Object as defined by the relation, answer "yes"; otherwise, answer "no". Answer with only "yes" or "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_etgpo_node_x_greater-tg --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively.

You need to decide whether the relation holds between the Subject and the Object entities in the query sentence. Focus on the *core meaning* of the relation, not superficial word matches with the support sentence. Consider the broader context of the query sentence and how the relationship might apply even if the specific entities or wording are different.  Recognize that relationships can exist even if the query uses different phrasing or figurative language (e.g., '"'"'like,'"'"' '"'"'similar to'"'"') to express the connection. Adapt your reasoning to the specific context of the query; a relationship that applies to cities might not directly apply to events in the same way. If the query demonstrates the same underlying relationship between the Subject and Object as defined by the relation, answer "yes ." otherwise, answer "no".'
