#!/usr/bin/env bash
set -euo pipefail
mkdir -p outputs/logs outputs/opt_prompt

# Generated from all_the_prompts.txt
# Each CODE block is passed as the instruction split; answer/input splits come from agents.agent_prompts.
# Commands run with nohup in the background.
# All commands still use cuda:0.
# Prompt blocks: 167
# Empty-status non-empty prompt blocks: 10
# Empty-status empty prompt blocks skipped: 43
# Status running/done blocks skipped: 114
# Other non-empty status blocks skipped: 0
# Exact duplicate non-empty blocks skipped: 0

nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_rpo_node_y_gradpo-gen_random --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and Object elements, which are indicated with the subject and object tags, respectively. 

To determine if the relation holds among the Subject and Object elements in the query sentence, strictly follow these steps:
1. **Verify the subject and object types**: The subject must be the entity type expected by the relation (e.g., "org" for organization, "per" for person). The object must match the relation'"'"'s definition (e.g., "org:stateorprovince_of_headquarters" requires the object to be a state/province, not a city or location). If the subject is a location (e.g., "Kennedy Space Center"), it must be explicitly tied to an organization (e.g., NASA) as its headquarters. 
2. **Verify the relationship**: Confirm that the query sentence explicitly links the Subject and Object as per the relation'"'"'s description. For example, "org:stateorprovince_of_headquarters" requires the subject to be an organization (e.g., "NASA") and the object to be a state/province (e.g., "Florida"), not a location (e.g., "Kennedy Space Center"). For "org:political/religious_affiliation," the object must be the organization'"'"'s actual political or religious affiliation (e.g., "Islamist"), not a role, descriptor, or faction. 
3. **Avoid role vs. person confusion**: If the object is a role (e.g., "chief executive") or title (e.g., "Rep."), it does not satisfy relations requiring a person (e.g., "employee_of"). Similarly, ensure the subject is the correct entity type (e.g., "org" for organizations, "per" for people). For "org:stateorprovince_of_headquarters," the subject must be an organization (e.g., "NASA"), not a location (e.g., "Kennedy Space Center"), unless the sentence explicitly states the location is the organization'"'"'s headquarters. 
4. **Focus on explicit connections**: Only answer "yes" if the query sentence directly establishes the relation between the subject and object as defined. This includes ensuring the object is the correct entity type (e.g., "state/province" for headquarters, "political/religious affiliation" for org:political/religious_affiliation) and that the subject is the correct entity type for the relation. 

If the relation holds, answer "yes"; otherwise, answer "no".' > outputs/logs/001_tacred_qwen_rpo_node_y_gradpo-gen_random.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_x_gradpo-gen_random --prompt 'You are given a relation name, its description, a support sentence which exemplifies the relation, and a query sentence. Analyze the relation description and the query sentence. The Subject and Object are labeled in the query sentence. Determine if the relation is expressed between the marked entities. Check the relation definition, the semantic type of each entity, the direction from the subject to Object, and whether the evidence is explicit or strongly implied. Treat the support sentence as a guide to the relation, not evidence for the query. Confirm that the relation direction is Subject-to-Object, that the Object has the required type or value, and that the query provides sufficient explicit or contextually implied evidence. Ignore any irrelevant entities or facts not directly stated in the query. If the relation holds in the query sentence, answer "yes"; otherwise answer "no".' > outputs/logs/002_tacred_qwen_evoprompt_node_x_gradpo-gen_random.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_etgpo_node_x_gradpo-gen_random --prompt 'You are given a relation name, a description of the relation in brackets, a support demonstration sentence that the relation, and a query sentence. A relation connects the Subject and the Object entities referenced by subject/object tags. You must determine if the relation holds between the tagged entities in the query sentence, following these rules:

1. **Entity Resolution**: Treat abbreviations (e.g., '"'"'Minn.'"'"') as their full forms (e.g., '"'"'Minnesota'"'"'), and ensure the object matches the required entity type (e.g., state/province vs. city vs. country).
2. **Explicit Matching**: Only use information explicitly stated in the query. Do not infer events (e.g., death) or relationships (e.g., familial ties) unless directly mentioned.
3. **Relation Type Precision**: Match the exact relationship type specified (e.g., '"'"'familial'"'"' vs. '"'"'friendship'"'"'). Do not conflate non-familial roles with familial relations.
4. **Role Implication Awareness**: Recognize that certain roles (e.g., '"'"'managing principal'"'"') inherently imply specific relationships (e.g., '"'"'shareholder'"'"') even if not explicitly stated.
5. **Geographic Hierarchy**: Distinguish between sovereign countries (e.g., '"'"'Cuba'"'"') and subnational entities (e.g., '"'"'California'"'"'). A country cannot satisfy a relation requiring a state/province.

Answer '"'"'yes'"'"' if the relation holds under these constraints; otherwise, answer '"'"'no'"'"'.' > outputs/logs/003_tacred_qwen_etgpo_node_x_gradpo-gen_random.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_rpo_node_y_gradpo-gen_random --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively. Your task is to determine whether the *specific relation* described holds between the Subject and the Object entities in the *query sentence*. Carefully examine the query sentence and consider the relationship between the subject and object entities. Do not answer "yes" simply because the subject and object are related in a general sense; verify that the query sentence explicitly or implicitly expresses the specified relation. Base your decision solely on the content of the query sentence. Ignore the support sentence.

When evaluating whether a relation holds, focus on the *core meaning* of the relation. Consider that the query sentence may express the relation using different phrasing or terminology than the relation description. Look for synonyms and related concepts that indicate the presence of the relation. Pay attention to context clues and implied relationships; the relation does not always need to be stated explicitly. Look beyond surface-level phrasing.

Avoid being distracted by surrounding details or circumstantial information within the query sentence that do not directly establish the relation. Prioritize understanding the core relationship between the subject and object, even if it is not stated using the exact words from the relation description. Consider the overall meaning of the sentence, even if the relationship is expressed indirectly.

To help you reason, consider these questions before answering:
* Does the sentence state or strongly imply a connection between the subject and the object that aligns with the relation description?
* Are there keywords or phrases that are closely associated with the relation, even if they are not exact synonyms?
* Could a reasonable person, knowing the relation description, conclude that the subject and object are connected in this way based only on the query sentence?
* **Specifically, identify the words or phrases in the query sentence that relate to the subject and object and explain how they suggest the relation. If the relation is not explicitly stated, what is the implied connection?**

Pay close attention to the entities themselves. Are you focusing on the correct entities as the subject and object? Confirm you'"'"'ve correctly identified which entity corresponds to which role.

Be mindful of potential ambiguities. Does the sentence present multiple possible interpretations? If so, choose the interpretation that best supports the relation.

Do not let pronouns or other linguistic complexities obscure the core meaning of the sentence. Focus on the concrete information presented.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".' > outputs/logs/004_tacred_gemma_rpo_node_y_gradpo-gen_random.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_evoprompt_node_x_gradpo-gen_random --prompt 'You will be provided with a relation name, a detailed description of the relation, a support sentence to demonstrate the relation'"'"'s core characteristics, and a query sentence. Examine the relation description, then carefully analyze the query sentence. The Subject and Object are clearly identified. First, identify the tagged Subject and Object. Then, verify the consistency between the relation’s definition, the entities’ semantic roles, the intended direction, and the presence of supporting evidence, whether directly stated or logically inferable. Pay attention to potential ambiguities in the query sentence. Evaluate solely on the information presented within the query sentence; external information is irrelevant. Treat the support sentence as a purely illustrative example; do not incorporate any information from it into your judgment. Respond with a clear '"'"'yes'"'"' or '"'"'no'"'"' to indicate whether the relation is confirmed, considering only the information presented within the query sentence.' > outputs/logs/005_tacred_gemma_evoprompt_node_x_gradpo-gen_random.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_etgpo_node_x_gradpo-gen_random --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively.

Your task is to determine whether the relation holds between the Subject and the Object entities in the query sentence. Focus on the *meaning* of the relationship described, not just the presence of shared words. Consider the broader context and what the relationship *represents*, not just whether the entities appear together. 

When evaluating, avoid fixating on specific details from the support sentence. Generalize the relational pattern to apply to different entities and contexts. The support sentence is an example; the query sentence may use different entities or phrasing to express the same relationship.

Be mindful of nuances in meaning. The relation type describes a specific connection; do not infer the relationship unless the connection is clearly and directly present in the query sentence, even if related concepts are mentioned. Focus on the *core* of the relation.

If the relation holds between the Subject and the Object entities in the query sentence, indicate "yes"; otherwise, indicate "no".' > outputs/logs/006_tacred_gemma_etgpo_node_x_gradpo-gen_random.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_rpo_node_x_gradpo-gen_random --prompt 'You are given a relation name, a description of the relation in brackets, a support instance which one exemplifies the relation, and a query sentence. The relation connects a **subject entity** and an **object entity**, which are marked with the <subject> and <object> tags, respectively. Your task is to determine whether the relation described in the support instance is valid between the subject and object entities in the query sentence.  

**Key Steps:**  
1. **Identify the subject and object entities** in the query sentence (they are marked with <subject> and <object> tags).  
2. **Analyze the relation** based on the provided description and the support instance. The relation must be a direct, specific connection between the subject and object entities as defined in the description.  
3. **Check the query sentence** for explicit evidence of the relation. If the subject and object entities in the query are not connected by the relation described (e.g., the object is not the correct entity type, or the connection is not explicitly stated), answer "no."  

Take the case of the relation "director," the subject (e.g., a film) must be connected to the object (e.g., a person) through the relation described in the support instance. If the object as the query is a genre or a different entity type, the answer is "no."  

If the relation is valid between the subject and object entities in the query sentence, answer "yes"; otherwise, answer "no."' > outputs/logs/007_fewrel_qwen_rpo_node_x_gradpo-gen_random.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_rpo_node_y_gradpo-gen_random --prompt 'You are given a specified relation, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively.
You need to determine if the query sentence expresses the given relation between the Subject and the Object entities, even if it’s not stated directly.

Consider the support instance as an example of the relation. However, it might not be directly applicable to every query. Focus on understanding the *type* of relationship described in the support instance, not on finding a word-for-word match.

Then the query sentence, at its heart, describes the same kind of relationship as the support instance? If yes, answer "yes"; otherwise, answer "no".' > outputs/logs/008_fewrel_gemma_rpo_node_y_gradpo-gen_random.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_evoprompt_node_y_gradpo-gen_random --prompt 'Decide whether the given relation accurately depicts the specified relationship between the tagged concept and Object entities in the query sentence. The support sentence exemplifies the relation; consider it for understanding the relation’s nature, but focus solely on the query sentence for evaluating the presence of this relation. Verify the relation’s definition, entity roles, and whether the relationship is explicitly stated or reasonably inferred from the query. Answer "yes" if the relation accurately reflects the relationship between the Subject and Object in the query; otherwise answer "no".' > outputs/logs/009_fewrel_gemma_evoprompt_node_y_gradpo-gen_random.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_etgpo_node_x_gradpo-gen_random --prompt 'You are given this relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the item entities. The Subject and the item entities are indicated with the subject and object tags, respectively.

You need to decide whether the relation holds between the Subject and the item entities in the query sentence. Focus on the *core meaning* of the relation, not superficial word matches with the support sentence. Consider the broader context of the query sentence and how the relationship might apply even if the specific entities or wording are different. Recognize that relationships can exist even if the query uses different phrasing or figurative language (e.g., '"'"'like,'"'"' '"'"'similar to'"'"') to express the connection. Adapt your reasoning to the specific context of the query; a relationship that applies to cities might not directly apply to events in the same way. If the query demonstrates a the same underlying relationship between the Subject and Object as defined by the relation, answer "yes"; otherwise, answer "no".' > outputs/logs/010_fewrel_gemma_etgpo_node_x_gradpo-gen_random.log 2>&1 &
