python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 8 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_x_gradpo-gen --prompt 'You are told given a relation name, its description, a support text that demonstrates the relation, and a query sentence. Analyze the relation description and the query sentence. The Subject and Object are labeled in the query sentence. Evaluate if the relation is expressed between the marked entities. Check the relation definition, the semantic type of each entity, the direction from Subject to Object, and whether the evidence is explicit or strongly implied. Treat the support sentence as a guide to the relation, not evidence for the query. Confirm that the relation direction is Subject-to-Object, that the Object has the required type or value, and that the query provides sufficient explicit or contextually implied evidence. Ignore any irrelevant entities or facts not directly stated in the query. If the relation holds in the query sentence, answer "yes"; otherwise answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 8 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_x_gradpo-prob --prompt 'The provided relation name, its description, a support example that exemplifies the relation, and a query sentence. Analyze the relation description and the query sentence. The Subject and Object are labeled in the query sentence. Check if the relation is expressed between the marked entities. Check the relation definition, the semantic type of each entity, the direction from Subject to Object, and whether the evidence is explicit or strongly implied. Treat the support sentence as a guide to the relation, not evidence for the query. Confirm that the relation direction is Subject-to-Object, that the Object has the required type or value, and that the query provides sufficient explicit or contextually implied evidence. Ignore any irrelevant entities or facts not directly stated in the query. If the relation holds in the query sentence, answer "yes"; otherwise answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 8 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_y --prompt 'You are given a relation name, its description, an example sentence, and a query. Analyze the relation and query for consistency and check whether the relation is properly instantiated between the labeled Subject and Object. Analyze the relation definition, semantic roles and types of entities, and the direction of the relation. Determine whether the evidence is directly mentioned or clearly implied. Use the support sentence only as a template for the relation. Do not consider external or unrelated information. Ensure the relation direction is from Subject to Object, that the entities match the required semantic roles, and that the evidence is clearly or strongly expressed. Answer '"'"'yes'"'"' only if the relation is clearly or strongly expressed between the Subject and Object in the query; otherwise, answer '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 8 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_y_greater --prompt 'Given are given a relation name, its description, an example sentence, and a query. Analyze the relation and query for consistency and check whether the relation is properly instantiated between the labeled Subject and Object. Analyze the relation definition, semantic roles and types of entities, and the direction of the relation. Determine whether the evidence is directly mentioned or clearly implied. Use the support sentence only as a template for the relation. Do not consider external or unrelated information. Ensure the relation direction is from Subject to Object, that the entities match the required semantic roles, and that the evidence is clearly or strongly expressed. Answer '"'"'yes'"'"' only if the relation is clearly or strongly expressed between the Subject and Object in the query; otherwise, answer '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 8 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_y_gradpo-gen --prompt 'You are given a relation name, its description, an example sentence, and a query. Analyze the relation and query for consistency and check whether the relation is properly instantiated between the labeled Subject and Object. Analyze the relation definition, semantic roles and types of entities, and the direction of the relation. Determine whether the evidence is directly mentioned or clearly implied. Use the provided sentence only as a template for the relation. Do not consider external or unrelated information. Ensure the relation direction is from Subject to Object, that the entities match the required semantic roles, and that the evidence is clearly or strongly expressed. Respond '"'"'yes'"'"' only if the relation is clearly or strongly expressed between the Subject and Object in the query; otherwise, respond '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 8 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_etgpo_node_x --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and the Object entities indicated by subject/object tags. You must determine if the relation holds between the tagged entities in the query sentence, following these rules:

1. **Entity Resolution**: Treat abbreviations (e.g., '"'"'Minn.'"'"') as their full forms (e.g., '"'"'Minnesota'"'"'), and ensure the object matches the required entity type (e.g., state/province vs. city vs. country).
2. **Explicit Matching**: Only use information explicitly stated in the query. Do not infer events (e.g., death) or relationships (e.g., familial ties) unless directly mentioned.
3. **Relation Type Precision**: Match the exact relationship type specified (e.g., '"'"'familial'"'"' vs. '"'"'friendship'"'"'). Do not conflate non-familial roles with familial relations.
4. **Role Implication Awareness**: Recognize that certain roles (e.g., '"'"'managing principal'"'"') inherently imply specific relationships (e.g., '"'"'shareholder'"'"') even if not explicitly stated.
5. **Geographic Hierarchy**: Distinguish between sovereign countries (e.g., '"'"'Cuba'"'"') and subnational entities (e.g., '"'"'California'"'"'). A country cannot satisfy a relation requiring a state/province.

Answer '"'"'yes'"'"' if the relation holds under these constraints; otherwise, answer '"'"'no'"'"'.'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 8 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_initial_prompt --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively. 
You need to decide whether the relation holds between the Subject and the Object entities in the query sentence.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 8 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_rpo_node_x --prompt 'You are given a relation name, a description of the relation in brackets, and a query sentence.

Your task is to determine whether the *specific relation* described holds between the Subject and the Object entities in the *query sentence*. The Subject and the Object entities are indicated with the subject and object tags, respectively. Carefully examine the query sentence, paying close attention to keywords and phrases commonly associated with the specified relation.

Consider the following:

*   **Explicit Statements:** Look for direct statements that express the relation (e.g., "is a subsidiary of," "was born in").
*   **Strong Indicators:** Recognize that relations can be implied or indicated through related language. For example, "native of" often implies "city of birth," and "subsidiary of" directly indicates an organizational relationship.
*   **Contextual Clues:** Evaluate the surrounding context to confirm the relationship.

Do not answer "yes" unless the query sentence explicitly or strongly implies the specified relation. Base your decision *solely* on the content of the query sentence. Ignore any support examples provided.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'