#!/usr/bin/env bash
set -euo pipefail
mkdir -p outputs/logs outputs/opt_prompt

# Generated from all_the_prompts.txt
# Each CODE block is passed as the instruction split; answer/input splits come from agents.agent_prompts.
# Commands run with nohup in the background.
# All commands still use cuda:0.
# Prompt blocks: 124
# Empty-status non-empty prompt blocks: 16
# Empty-status empty prompt blocks skipped: 108
# Status running/done blocks skipped: 0
# Other non-empty status blocks skipped: 0
# Exact duplicate non-empty blocks skipped: 1

nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_initial_prompt --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively. 
You need to decide whether the relation holds between the Subject and the Object entities in the query sentence.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".' > outputs/logs/001_tacred_qwen_initial_prompt.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_rpo_node_x --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and Object entities, which are indicated with the subject and object tags, respectively. 

To determine if the relation holds between the Subject and Object entities in the query sentence, strictly follow these steps:
1. **Verify the subject and object types**: 
   - For relations starting with "org:", the **subject must be an organization** (not a person or role). 
   - The **object must align with the relation'"'"'s definition** (e.g., "org:subsidiaries" requires a subsidiary entity, not a role or category; "org:political/religious_affiliation" accepts a religious or political category, not a person). 
2. **Check the relationship**: Confirm that the query sentence explicitly links the Subject and Object as per the relation'"'"'s description. For example, "org:subsidiaries" requires a hierarchical connection between an organization and its subsidiary (e.g., "Company A owns Company B"), not a personal or abstract relationship. 
3. **Recognize object types**: 
   - The object can be a **specific entity** (e.g., "US-based Ryder Public Transportation Services") or a **category** (e.g., "Christian", "Islamist") if the relation explicitly allows it. 
   - Avoid treating abstract terms (e.g., "Christian") as roles or people unless the relation'"'"'s description explicitly permits it. 
4. **Focus on explicit connections**: Only answer "yes" if the query sentence directly establishes the relation between the subject and object as defined. For example, "org:number_of_employees/members" requires a numerical value (e.g., "42,000") to indicate the count, not a vague term like "many." 

If the relation holds, answer "yes"; otherwise, answer "no".' > outputs/logs/002_tacred_qwen_rpo_node_x.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_rpo_node_x_greater --prompt 'I are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and Object entities, which are indicated with the subject and object tags, respectively. 

To determine if the relation holds between the Subject and Object entities in the query sentence, strictly follow these steps:
1. **Verify the subject and object types**: 
   - For relations starting with "org:", the **subject must be an organization** (not a person or role). 
   - The **object must align with the relation'"'"'s definition** (e.g., "org:subsidiaries" requires a subsidiary entity, not a role or category; "org:political/religious_affiliation" accepts a religious or political category, not a person). 
2. **Check the relationship**: Confirm that the query sentence explicitly links the Subject and Object as per the relation'"'"'s description. For example, "org:subsidiaries" requires a hierarchical connection between an organization and its subsidiary (e.g., "Company A owns Company B"), not a personal or abstract relationship. 
3. **Recognize object types**: 
   - The object can be a **specific entity** (e.g., "US-based Ryder Public Transportation Services") or a **category** (e.g., "Christian", "Islamist") if the relation explicitly allows it. 
   - Avoid treating abstract terms (e.g., "Christian") as roles or people unless the relation'"'"'s description explicitly permits it. 
4. **Focus on explicit connections**: Only answer "yes" if the query sentence directly establishes the relation between the subject and object as defined. For example, "org:number_of_employees/members" requires a numerical value (e.g., "42,000") to indicate the count, not a vague term like "many." 

If the relation holds, answer "yes"; otherwise, answer "no".' > outputs/logs/003_tacred_qwen_rpo_node_x_greater.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_rpo_node_x_greater-tg --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and Object entities, which are indicated with the subject and object tags, respectively. 

To determine if the relation holds between the Subject and Object entities in the query sentence, strictly follow these steps:
1. **Verify the subject and object types**: 
   - For relations starting with "org:", the **subject must be an organization** (not a person or role). 
   - The **object must align with the relation'"'"'s definition** (e.g., "org:subsidiaries" requires a subsidiary entity, not a role or category; "org:political/religious_affiliation" accepts a religious or political category, not a person). 
2. **Check the relationship**: Confirm that the query sentence explicitly links the Subject and Object as per the relation'"'"'s description. For example, "org:subsidiaries" requires a hierarchical connection between an organization and its subsidiary (e.g., "Company A owns Company B"), not a personal or abstract relationship. 
3. **Recognize object types**: 
   - The object can be a **specific entity** (e.g., "US-based Ryder Public Transportation Services") or a **category** (e.g., "Christian", "Islamist") if the relation explicitly allows it. 
   - Avoid treating abstract terms (e.g., "Christian") as roles or people unless the relation'"'"'s description explicitly permits it. 
4. **Focus on explicit connections**: Only answer "yes" if the query sentence directly establishes the relation between the subject and object as defined. For example, "org:number_of_employees/members" requires a numerical value (e.g., "42,000") to indicate the count, not a vague term like "many." 

If the relation holds, answer "your"; otherwise, answer "no".' > outputs/logs/004_tacred_qwen_rpo_node_x_greater-tg.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_rpo_node_x_gradpo-gen --prompt 'You are given a relation name, a definition of the relation in bracketed text, a support example sentence exemplifying the relation, and a query inquiry sentence. A relation connects the Subject and Object entities, which are indicated with the subject and object tags, respectively. 

To determine if the relation holds between the Subject and Object entities in the query sentence, strictly follow these steps:
1. **Verify the subject and object types**: 
   - For relations starting with "org:", the **subject must be an organization** (not a person or role). 
   - The **object must align with the relation'"'"'s definition** (e.g., "org:subsidiaries" requires a subsidiary entity, not a role or category; "org:political/religious_affiliation" accepts a religious or political category, not a person). 
2. **Check the relationship**: Confirm that the query sentence explicitly links the Subject and Object as per the relation'"'"'s description. For example, "org:subsidiaries" requires a hierarchical connection between an organization and its subsidiary (e.g., "Company A owns Company B"), not a personal or abstract relationship. 
3. **Recognize object types**: 
   - The object can be a **specific entity** (e.g., "US-based Ryder Public Transportation Services") or a **category** (e.g., "Christian", "Islamist") if the relation explicitly allows it. 
   - Avoid treating abstract terms (e.g., "Christian") as roles or people unless the relation'"'"'s definition explicitly permits it. 
4. **Focus on explicit connections**: Only answer "yes" if the query sentence directly establishes the relation between the subject and object as defined. For example, "org:number_of_employees/members" requires a numerical value (e.g., "42,000") to indicate the count, not a vague term like "many." 

If the relation holds, answer "yes"; otherwise, answer "no".' > outputs/logs/005_tacred_qwen_rpo_node_x_gradpo-gen.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_rpo_node_x_gradpo-prob --prompt 'You are given a relation name, a description of the relation in [brackets], a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and Object entities, which are indicated with the subject and object tags, respectively. 

To determine if the relation holds between the Subject and Object entities in the query sentence, strictly follow these steps:
1. **Verify the subject and object types**: 
   - For relations starting with "org:", the subject must be an organization (not a person or role). 
   - The object must align with the relation'"'"'s definition (e.g., "org:subsidiaries" requires a subsidiary entity, not a role or category; "org:political/religious_affiliation" accepts a religious or political category, not a person). 
2. **Check the relationship**: Confirm that the query sentence explicitly links the Subject and Object as per the relation'"'"'s description. For example, "org:subsidiaries" requires a hierarchical connection between an organization and its subsidiary (e.g., "Company A owns Company B"), not a personal or abstract relationship. 
3. **Recognize object types**: 
   - The object can be a specific entity (e.g., "US-based Ryder Public Transportation Services") or a category (e.g., "Christian", "Islamist") if the relation explicitly allows it. 
   - Avoid treating abstract terms (e.g., "Christian") as roles or people unless the relation'"'"'s description explicitly permits it. 
4. **Focus on explicit connections**: Only answer "yes" if the query sentence directly establishes the relation between the subject and object as defined. For example, "org:number_of_employees/members" requires a numerical value (e.g., "42,000") to indicate the count, not a vague term like "many." 

If the relation holds, answer "yes"; otherwise, answer "no".' > outputs/logs/006_tacred_qwen_rpo_node_x_gradpo-prob.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_rpo_node_y --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and Object entities, which are indicated with the subject and object tags, respectively. 

To determine if the relation holds between the Subject and Object entities in the query sentence, strictly follow these steps:
1. **Verify the subject and object types**: The subject must be the entity type expected by the relation (e.g., "org" for organization, "per" for person). The object must match the relation'"'"'s definition (e.g., "org:stateorprovince_of_headquarters" requires the object to be a state/province, not a city or location). If the subject is a location (e.g., "Kennedy Space Center"), it must be explicitly tied to an organization (e.g., NASA) as its headquarters. 
2. **Check the relationship**: Confirm that the query sentence explicitly links the Subject and Object as per the relation'"'"'s description. For example, "org:stateorprovince_of_headquarters" requires the subject to be an organization (e.g., "NASA") and the object to be a state/province (e.g., "Florida"), not a location (e.g., "Kennedy Space Center"). For "org:political/religious_affiliation," the object must be the organization'"'"'s actual political or religious affiliation (e.g., "Islamist"), not a role, descriptor, or faction. 
3. **Avoid role vs. person confusion**: If the object is a role (e.g., "chief executive") or title (e.g., "Rep."), it does not satisfy relations requiring a person (e.g., "employee_of"). Similarly, ensure the subject is the correct entity type (e.g., "org" for organizations, "per" for people). For "org:stateorprovince_of_headquarters," the subject must be an organization (e.g., "NASA"), not a location (e.g., "Kennedy Space Center"), unless the sentence explicitly states the location is the organization'"'"'s headquarters. 
4. **Focus on explicit connections**: Only answer "yes" if the query sentence directly establishes the relation between the subject and object as defined. This includes ensuring the object is the correct entity type (e.g., "state/province" for headquarters, "political/religious affiliation" for org:political/religious_affiliation) and that the subject is the correct entity type for the relation. 

If the relation holds, answer "yes"; otherwise, answer "no".' > outputs/logs/007_tacred_qwen_rpo_node_y.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_rpo_node_y_greater --prompt 'Class are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and Object entities, which are indicated with the subject and object tags, respectively. 

To determine if the relation holds between the Subject and Object entities in the query sentence, strictly follow these steps:
1. **Verify the subject and object types**: The subject must be the entity type expected by the relation (e.g., "org" for organization, "per" for person). The object must match the relation'"'"'s definition (e.g., "org:stateorprovince_of_headquarters" requires the object to be a state/province, not a city or location). If the subject is a location (e.g., "Kennedy Space Center"), it must be explicitly tied to an organization (e.g., NASA) as its headquarters. 
2. **Check the relationship**: Confirm that the query sentence explicitly links the Subject and Object as per the relation'"'"'s description. For example, "org:stateorprovince_of_headquarters" requires the subject to be an organization (e.g., "NASA") and the object to be a state/province (e.g., "Florida"), not a location (e.g., "Kennedy Space Center"). For "org:political/religious_affiliation," the object must be the organization'"'"'s actual political or religious affiliation (e.g., "Islamist"), not a role, descriptor, or faction. 
3. **Avoid role vs. person confusion**: If the object is a role (e.g., "chief executive") or title (e.g., "Rep."), it does not satisfy relations requiring a person (e.g., "employee_of"). Similarly, ensure the subject is the correct entity type (e.g., "org" for organizations, "per" for people). For "org:stateorprovince_of_headquarters," the subject must be an organization (e.g., "NASA"), not a location (e.g., "Kennedy Space Center"), unless the sentence explicitly states the location is the organization'"'"'s headquarters. 
4. **Focus on explicit connections**: Only answer "yes" if the query sentence directly establishes the relation between the subject and object as defined. This includes ensuring the object is the correct entity type (e.g., "state/province" for headquarters, "political/religious affiliation" for org:political/religious_affiliation) and that the subject is the correct entity type for the relation. 

If the relation holds, answer "yes"; otherwise, answer "no".' > outputs/logs/008_tacred_qwen_rpo_node_y_greater.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_rpo_node_y_greater-tg --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and Object entities, which are indicated with the subject and object tags, respectively. 

To determine if the relation holds between the Subject and Object entities in the query sentence, strictly follow these steps:
1. **Verify the subject and object types**: The subject must be the entity type expected by the relation (e.g., "org" for organization, "per" for person). The object must match the relation'"'"'s definition (e.g., "org:stateorprovince_of_headquarters" requires the object to be a state/province, not a city or location). If the subject is a location (e.g., "Kennedy Space Center"), it must be explicitly tied to an organization (e.g., NASA) as its headquarters. 
2. **Check the relationship**: Confirm that the query sentence explicitly links the Subject and Object as per the relation'"'"'s description. For example, "org:stateorprovince_of_headquarters" requires the subject to be an organization (e.g., "NASA") and the object to be a state/province (e.g., "Florida"), not a location (e.g., "Kennedy Space Center"). For "org:political/religious_affiliation," the object must be the organization'"'"'s actual political or religious affiliation (e.g., "Islamist"), not a role, descriptor, or faction. 
3. **Avoid role vs. person confusion**: If the object is a role (e.g., "chief executive") or title (e.g., "Rep."), it does not satisfy relations requiring a person (e.g., "employee_of"). Similarly, ensure the subject is the correct entity type (e.g., "org" for organizations, "per" for people). For "org:stateorprovince_of_headquarters," the subject must be an organization (e.g., "NASA"), not a location (e.g., "Kennedy Space Center"), unless the sentence explicitly states the location is the organization'"'"'s headquarters. 
4. **Focus on explicit connections**: Only answer "yes" if the query sentence directly establishes the relation between the subject and object as defined. This includes ensuring the object is the correct entity type (e.g., "state/province" for headquarters, "political/religious affiliation" for org:political/religious_affiliation) and that the subject is the correct entity type for the relation. 

If the relation holds, answer "1"; otherwise, answer "no".' > outputs/logs/009_tacred_qwen_rpo_node_y_greater-tg.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_rpo_node_y_gradpo-gen --prompt 'You are given a relation property, a description of the relation in curly braces, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and Object entities, which are indicated with the subject and object tags, respectively. 

To determine if the relation holds between the Subject and Object entities in the query sentence, strictly follow these steps:
1. **Verify the subject and object types**: The subject must be the entity type expected by the relation (e.g., "org" for organization, "per" for person). The object must match the relation'"'"'s definition (e.g., "org:stateorarea_of_headquarters" requires the object to be an area, not a city or location). If the subject is a location (e.g., "Kennedy Space Center"), it must be explicitly tied to an organization (e.g., NASA) as its headquarters. 
2. **Check the relationship**: Confirm that the query sentence explicitly links the Subject and Object as per the relation'"'"'s description. For example, "org:stateorarea_of_headquarters" requires the subject to be an organization (e.g., "NASA") and the object to be an area (e.g., "Florida"), not a location (e.g., "Kennedy Space Center"). For "org:political/religious_affiliation," the object must be the organization'"'"'s actual political or religious affiliation (e.g., "Islamist"), not a role, descriptor, or faction. 
3. **Avoid role vs. person confusion**: If the object is a role (e.g., "chief executive") or title (e.g., "Rep."), it does not satisfy relations requiring a person (e.g., "employee_of"). Similarly, ensure the subject is the correct entity type (e.g., "org" for organizations, "per" for people). For "org:stateorarea_of_headquarters," the subject must be an organization (e.g., "NASA"), not a location (e.g., "Kennedy Space Center"), unless the sentence explicitly states the location is the organization'"'"'s headquarters. 
4. **Focus on explicit connections**: Only confirm if the query sentence directly establishes the relation between the subject and object as defined. This includes ensuring the object is the correct entity type (e.g., "area" for headquarters, "political/religious affiliation" for org:political/religious_affiliation) and that the subject is the correct entity type for the relation. 

If the relation holds, answer "yes"; otherwise, answer "no".' > outputs/logs/010_tacred_qwen_rpo_node_y_gradpo-gen.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_rpo_node_y_gradpo-prob --prompt 'You are given a relation , a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence. A relation connects the Subject and Object entities, which are indicated with the subject and object tags, respectively. 

To determine if the relation holds between the Subject and Object entities in the query sentence, strictly follow these steps:
1. **Verify the subject and object types**: The subject must be the entity type expected by the relation (e.g., "org" for organization, "per" for person). The object must match the relation'"'"'s definition (e.g., "org:stateorprovince_of_headquarters" requires the object to be a state/province, not a city or location). If the subject is a location (e.g., "Kennedy Space Center"), it must be explicitly tied to an organization (e.g., NASA) as its headquarters. 
2. **Check the relationship**: Confirm that the query sentence explicitly links the Subject and Object as per the relation'"'"'s description. For example, "org:stateorprovince_of_headquarters" requires the subject to be an organization (e.g., "NASA") and the object to be a state/province (e.g., "Florida"), not a location (e.g., "Kennedy Space Center"). For "org:political/religious_affiliation," the object must be the organization'"'"'s actual political or religious affiliation (e.g., "Islamist"), not a role, descriptor, or faction. 
3. **Avoid role vs. person confusion**: If the object is a role (e.g., "chief executive") or title (e.g., "Rep."), it does not satisfy relations requiring a person (e.g., "employee_of"). Similarly, ensure the subject is the correct entity type (e.g., "org" for organizations, "per" for people). For "org:stateorprovince_of_headquarters," the subject must be an organization (e.g., "NASA"), not a location (e.g., "Kennedy Space Center"), unless the sentence explicitly states the location is the organization'"'"'s headquarters. 
4. **Focus on explicit connections**: Only answer "yes" if the query sentence directly establishes the relation between the subject and object as defined. This includes ensuring the object is the correct entity type (e.g., "state/province" for headquarters, "political/religious affiliation" for org:political/religious_affiliation) and that the subject is the correct entity type for the relation. 

If the relation holds, answer "yes"; otherwise, answer "no".' > outputs/logs/011_tacred_qwen_rpo_node_y_gradpo-prob.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_x --prompt 'You are given a relation name, its description, a support sentence that exemplifies the relation, and a query sentence. Analyze the relation description and the query sentence. The Subject and Object are labeled in the query sentence. Determine if the relation is expressed between the marked entities. Check the relation definition, the semantic type of each entity, the direction from Subject to Object, and whether the evidence is explicit or strongly implied. Treat the support sentence as a guide to the relation, not evidence for the query. Confirm that the relation direction is Subject-to-Object, that the Object has the required type or value, and that the query provides sufficient explicit or contextually implied evidence. Ignore any irrelevant entities or facts not directly stated in the query. If the relation holds in the query sentence, answer "yes"; otherwise answer "no".' > outputs/logs/012_tacred_qwen_evoprompt_node_x.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_qwen_evoprompt_node_y --prompt 'You are given a relation name, its description, an example sentence, and a query. Analyze the relation and query for consistency and check whether the relation is properly instantiated between the labeled Subject and Object. Analyze the relation definition, semantic roles and types of entities, and the direction of the relation. Determine whether the evidence is directly mentioned or clearly implied. Use the support sentence only as a template for the relation. Do not consider external or unrelated information. Ensure the relation direction is from Subject to Object, that the entities match the required semantic roles, and that the evidence is clearly or strongly expressed. Answer '"'"'yes'"'"' only if the relation is clearly or strongly expressed between the Subject and Object in the query; otherwise, answer '"'"'no'"'"'.' > outputs/logs/013_tacred_qwen_evoprompt_node_y.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_tacred_test_episodes_1shots.pkl --dataset_core tacred --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code tacred_gemma_initial_prompt --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively. 
You need to decide whether the relation holds between the Subject and the Object entities in the query sentence.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".' > outputs/logs/014_tacred_gemma_initial_prompt.log 2>&1 &
nohup python -u codes/final_model_run_icl_dynamic_prompt.py --model Qwen/Qwen3-4B --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:0 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_qwen_initial_prompt --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively. 
You need to decide whether the relation holds between the Subject and the Object entities in the query sentence.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".' > outputs/logs/015_fewrel_qwen_initial_prompt.log 2>&1 &
