python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:3 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_rpo_node_x_greater --prompt 'To are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively. These are entities – consider their types and roles within the sentence. The prompt provides a description of the relation – use this in conjunction with the support instance to guide your reasoning.

You need to decide whether the relation holds between the Subject and the Object entities in the query sentence. The relation may be explicitly stated or implied through the context of the sentence. Carefully consider the surrounding words and phrases to determine if a connection exists.

If the relation holds between the Subject and the Object entities in the query sentence, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:3 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_rpo_node_x_gradpo-gen --prompt 'You are given a concept, a description of the relation in brackets, a example sentence exemplifying the relation, and a question.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively. These are entities – consider their types and roles within the sentence. The prompt provides a description of the relation – use this in conjunction with the example sentence to guide your reasoning.

You need to decide whether the relation holds between the Subject and the Object entities in the question. The relation may be explicitly stated or implied through the context of the sentence. Carefully consider the surrounding words and phrases to determine if a connection exists.

If the relation holds between the Subject and the Object entities in the question, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:3 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_rpo_node_y --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively.
You need to determine if the query sentence expresses the given relation between the Subject and the Object entities, even if it'"'"'s not stated directly.

Consider the support instance as an example of the relation. However, it might not be directly applicable to every query. Focus on understanding the *type* of relationship described in the support instance, not on finding a word-for-word match.

When evaluating the query sentence, focus on the core connection between the Subject and the Object. Ignore irrelevant details or specific locations unless they are essential to establishing the relation. Ask yourself: Does this sentence, at its heart, describe the same kind of relationship as the support instance?

If the query sentence expresses the relation between the Subject and the Object entities, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:3 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_rpo_node_y_greater-tg --prompt 'You are given a relation name, a description of the relation in brackets, a support sentence exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively.
You need to determine if the query sentence expresses the given relation between the Subject and the Object entities, even if it'"'"'s not stated directly.

Consider the support instance as an example of the relation. However, it might not be directly applicable to every query. Focus on understanding the *type* of relationship described in the support instance, not on finding a word-for-word match.

When evaluating the query sentence, focus on the core connection between the Subject and the Object. Ignore irrelevant details or specific locations unless they are essential to establishing the relation. Ask yourself: Does this sentence, at its heart, describe the same kind of relationship as the support instance?

If the query sentence expresses the relation between the Subject and the Object entities, answer "yes"! otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:3 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_rpo_node_y_gradpo-gen --prompt 'You are given a relation name, a description of the relation in brackets, a sentence serving as an example of the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively.
You need to determine if the query sentence expresses certain relation between the Subject and the Object entities, even if it'"'"'s not stated directly.

Consider the instance as an example of the relation. However, it might not be directly applicable to every query. Focus on understanding the *type* of relationship described in the support instance, not on finding a word-for-word match.

When evaluating the query sentence, focus on the core connection between the Subject and the Object. Ignore irrelevant details or specific locations unless they are essential to establishing the relation. Ask yourself: Does this sentence, at its heart, describe the same kind of relationship as the support instance?

If the query sentence expresses the relation between the Subject and the Object entities, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:3 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_rpo_node_y_gradpo-prob --prompt 'You are given a relation name, a description of the relation in brackets, a support instance exemplifying the relation, and a query sentence.

A relation connects the Subject and the Object entities. The Subject and the Object entities are indicated with the subject and object tags, respectively.
You need to determine if the query sentence expresses this given relation between the Subject and the Object entities, even if it'"'"'s not stated directly.

Consider the support instance as an example of the relation. However, it might not be directly applicable to every query. Focus on understanding the *type* of relationship described in the support instance, not on finding a word-for-word match.

When evaluating the query sentence, focus on the core connection between the Subject and the Object. Ignore irrelevant details or specific locations unless they are essential to establishing the relation. Ask yourself: Does this sentence, at its heart, describe the same kind of relationship as the support instance?

If the query sentence expresses the relation between the Subject and the Object entities, answer "yes"; otherwise, answer "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:3 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_evoprompt_node_x --prompt 'Read the relation description, then read the query sentence. The Subject and Object are already marked with tags. Evaluate the possibility of the given relation. Examine the Subject and Object entities, ensuring they align with the relation'"'"'s definition and context. Assess if the query sentence explicitly or implicitly conveys the required semantic relationship between the Subject and Object, and if the relation'"'"'s expected type is present. Focus solely on the query sentence'"'"'s content, avoiding any influence from the example sentence. The support sentence serves as a demonstration of the relation. Answer only "yes" or "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:3 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_evoprompt_node_x_lpo --prompt 'Read the relation description, then read the query sentence. The Subject and Object are already marked with tags. Carefully assess the query sentence. Determine if the query sentence expresses the target relation between the subject and object entities. The support sentence is provided as an example, but prioritize the query sentence when making your determination. Examine the Subject and Object entities, ensuring they align with the relation'"'"'s definition and context. Assess if the query sentence explicitly or implicitly conveys the required semantic relationship between the Subject and Object, and if the relation'"'"'s expected type is present. Focus solely on the query sentence'"'"'s content, ignoring the support sentence. The support sentence serves as a demonstration of the relation. Provide only "yes" or "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:3 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_evoprompt_node_x_greater --prompt 'Solve the relation description, then read the query sentence. The Subject and Object are already marked with tags. Evaluate the possibility of the given relation. Examine the Subject and Object entities, ensuring they align with the relation'"'"'s definition and context. Assess if the query sentence explicitly or implicitly conveys the required semantic relationship between the Subject and Object, and if the relation'"'"'s expected type is present. Focus solely on the query sentence'"'"'s content, avoiding any influence from the example sentence. The support sentence serves as a demonstration of the relation. Answer only "yes" or "no".'
python -u codes/final_model_run_icl_dynamic_prompt.py --model google/gemma-3-4b-it --dataset fs_fewrel_test_episodes_1shots.pkl --dataset_core fewrel --ways 5 --shots 1 --query 0 --cuda cuda:3 --ep_start 0 --ep_end 150000 --batch_size 15 --data_root data --output_dir outputs/opt_prompt --code fewrel_gemma_evoprompt_node_x_greater-tg --prompt 'Read the relation description, then read the query sentence. The Subject and Object are already marked with tags. Evaluate the possibility of the given relation. Examine the Subject and Object entities, ensuring they align with the relation'"'"'s definition and context. Assess if the query sentence explicitly or implicitly conveys the required semantic relationship between the Subject and Object, and if the relation'"'"'s expected type is present. Focus solely on the query sentence'"'"'s content, avoiding any influence from the example sentence. The support sentence serves as a demonstration of the relation. Answer only "yes'"'"''"'"' or "no".'
