"""Run one second-stage LPO refinement on an OpenBookQA prompt."""

from __future__ import annotations

import argparse

from prompt_optimization.cli_common import add_shared_arguments, build_context
from prompt_optimization.second_stage import run_lpo


def parse_args() -> argparse.Namespace:
    """Read the full-scale QA LPO configuration."""
    parser = argparse.ArgumentParser(description=__doc__)
    add_shared_arguments(parser, require_optimizer_model=True)
    parser.add_argument(
        "--train-sample-size",
        type=int,
        default=512,
        help="Training questions sampled to collect prompt feedback.",
    )
    parser.add_argument(
        "--feedback-examples",
        "--mistake-examples",
        dest="feedback_examples",
        type=int,
        default=3,
        help="Mixed correct and incorrect QA examples shown to LPO.",
    )
    parser.add_argument(
        "--max-locations",
        type=int,
        default=5,
        help="Maximum prompt locations LPO may select for editing.",
    )
    parser.add_argument(
        "--max-words-per-location",
        type=int,
        default=3,
        help="Maximum words allowed in each selected edit location.",
    )
    parser.add_argument(
        "--num-candidates",
        type=int,
        default=5,
        help="Number of rewritten prompt candidates generated by LPO.",
    )
    parser.add_argument(
        "--top-z",
        type=int,
        default=5,
        help="Top training-ranked candidates evaluated on full validation.",
    )
    args = parser.parse_args()
    positive_values = (
        args.train_sample_size,
        args.feedback_examples,
        args.max_locations,
        args.max_words_per_location,
        args.num_candidates,
        args.top_z,
    )
    if any(value <= 0 for value in positive_values):
        parser.error("All LPO size and count arguments must be positive.")
    return args


def main() -> None:
    """Build the QA context, run LPO, and release model memory."""
    args = parse_args()
    context = build_context(args, "lpo")
    try:
        summary = run_lpo(context, args)
        print(f"Saved QA LPO run to: {context.run_dir}")
        print(f"Validation accuracy gain: {summary['validation']['accuracy_gain']:+.4f}")
    finally:
        context.model_pool.close()


if __name__ == "__main__":
    main()
