#!/usr/bin/env bash
set -euo pipefail

# OpenBookQA non-reasoning: five source prompts x six refiners.
# Test evaluation remains disabled; selection uses 3 x 500 validation.
# nohup bash codes/run_openbookqa_second_stage_qwen.sh > codes/nohup_outs/openbookqa_second_stage_qwen.log 2>&1 &

[[ -f outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_5.txt ]] || { echo 'Missing first-stage prompt: outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_5.txt'; exit 1; }
[[ -f outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_10.txt ]] || { echo 'Missing first-stage prompt: outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_10.txt'; exit 1; }
[[ -f outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_5.txt ]] || { echo 'Missing first-stage prompt: outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_5.txt'; exit 1; }
[[ -f outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_10.txt ]] || { echo 'Missing first-stage prompt: outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_10.txt'; exit 1; }
[[ -f outputs/qa_prompt_optimization/non_reasoning/etgpo/openbookqa_non_reasoning_qwen_etgpo_qwen14opt_lambda1_fixed_vs1500/final_prompt.txt ]] || { echo 'Missing first-stage prompt: outputs/qa_prompt_optimization/non_reasoning/etgpo/openbookqa_non_reasoning_qwen_etgpo_qwen14opt_lambda1_fixed_vs1500/final_prompt.txt'; exit 1; }

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_lpo.py \
  --code openbookqa_non_reasoning_qwen_rpo5_lpo_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_5.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --optimizer-model Qwen/Qwen3-14B \
  --optimizer-device cuda:0 \
  --backend vllm \
  --gpu-memory-utilization 0.90 \
  --optimizer-max-new-tokens 10000 \
  --train-sample-size 512 \
  --feedback-examples 3 \
  --max-locations 5 \
  --max-words-per-location 3 \
  --num-candidates 5 \
  --top-z 5

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_greater.py \
  --code openbookqa_non_reasoning_qwen_rpo5_greater_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_5.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant greater \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 4 \
  --selection-batch-size 8 \
  --proposal-top-k 25 \
  --proposal-example-size 50 \
  --proposal-min-candidates 10 \
  --selection-top-mu 10 \
  --top-u 5 \
  --fluency-lambda 0.2 \
  --region-expansion-threshold 0.6

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_greater.py \
  --code openbookqa_non_reasoning_qwen_rpo5_greater_tg_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_5.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant greater_tg \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 4 \
  --selection-batch-size 8 \
  --proposal-top-k 25 \
  --proposal-example-size 50 \
  --proposal-min-candidates 10 \
  --selection-top-mu 10 \
  --top-u 5 \
  --fluency-lambda 0.2 \
  --region-expansion-threshold 0.6

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_rpo5_gradpo_gen_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_5.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant gen \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_rpo5_gradpo_prob_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_5.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant prob \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_rpo5_gradpo_gen_random_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_5.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant gen_random \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_lpo.py \
  --code openbookqa_non_reasoning_qwen_rpo10_lpo_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_10.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --optimizer-model Qwen/Qwen3-14B \
  --optimizer-device cuda:0 \
  --backend vllm \
  --gpu-memory-utilization 0.90 \
  --optimizer-max-new-tokens 10000 \
  --train-sample-size 512 \
  --feedback-examples 3 \
  --max-locations 5 \
  --max-words-per-location 3 \
  --num-candidates 5 \
  --top-z 5

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_greater.py \
  --code openbookqa_non_reasoning_qwen_rpo10_greater_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_10.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant greater \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 4 \
  --selection-batch-size 8 \
  --proposal-top-k 25 \
  --proposal-example-size 50 \
  --proposal-min-candidates 10 \
  --selection-top-mu 10 \
  --top-u 5 \
  --fluency-lambda 0.2 \
  --region-expansion-threshold 0.6

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_greater.py \
  --code openbookqa_non_reasoning_qwen_rpo10_greater_tg_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_10.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant greater_tg \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 4 \
  --selection-batch-size 8 \
  --proposal-top-k 25 \
  --proposal-example-size 50 \
  --proposal-min-candidates 10 \
  --selection-top-mu 10 \
  --top-u 5 \
  --fluency-lambda 0.2 \
  --region-expansion-threshold 0.6

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_rpo10_gradpo_gen_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_10.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant gen \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_rpo10_gradpo_prob_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_10.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant prob \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_rpo10_gradpo_gen_random_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/rpo/openbookqa_non_reasoning_qwen_rpo_qwen14opt_lambda1/prompt_iteration_10.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant gen_random \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_lpo.py \
  --code openbookqa_non_reasoning_qwen_evoprompt5_lpo_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_5.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --optimizer-model Qwen/Qwen3-14B \
  --optimizer-device cuda:0 \
  --backend vllm \
  --gpu-memory-utilization 0.90 \
  --optimizer-max-new-tokens 10000 \
  --train-sample-size 512 \
  --feedback-examples 3 \
  --max-locations 5 \
  --max-words-per-location 3 \
  --num-candidates 5 \
  --top-z 5

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_greater.py \
  --code openbookqa_non_reasoning_qwen_evoprompt5_greater_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_5.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant greater \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 4 \
  --selection-batch-size 8 \
  --proposal-top-k 25 \
  --proposal-example-size 50 \
  --proposal-min-candidates 10 \
  --selection-top-mu 10 \
  --top-u 5 \
  --fluency-lambda 0.2 \
  --region-expansion-threshold 0.6

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_greater.py \
  --code openbookqa_non_reasoning_qwen_evoprompt5_greater_tg_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_5.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant greater_tg \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 4 \
  --selection-batch-size 8 \
  --proposal-top-k 25 \
  --proposal-example-size 50 \
  --proposal-min-candidates 10 \
  --selection-top-mu 10 \
  --top-u 5 \
  --fluency-lambda 0.2 \
  --region-expansion-threshold 0.6

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_evoprompt5_gradpo_gen_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_5.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant gen \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_evoprompt5_gradpo_prob_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_5.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant prob \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_evoprompt5_gradpo_gen_random_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_5.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant gen_random \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_lpo.py \
  --code openbookqa_non_reasoning_qwen_evoprompt10_lpo_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_10.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --optimizer-model Qwen/Qwen3-14B \
  --optimizer-device cuda:0 \
  --backend vllm \
  --gpu-memory-utilization 0.90 \
  --optimizer-max-new-tokens 10000 \
  --train-sample-size 512 \
  --feedback-examples 3 \
  --max-locations 5 \
  --max-words-per-location 3 \
  --num-candidates 5 \
  --top-z 5

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_greater.py \
  --code openbookqa_non_reasoning_qwen_evoprompt10_greater_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_10.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant greater \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 4 \
  --selection-batch-size 8 \
  --proposal-top-k 25 \
  --proposal-example-size 50 \
  --proposal-min-candidates 10 \
  --selection-top-mu 10 \
  --top-u 5 \
  --fluency-lambda 0.2 \
  --region-expansion-threshold 0.6

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_greater.py \
  --code openbookqa_non_reasoning_qwen_evoprompt10_greater_tg_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_10.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant greater_tg \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 4 \
  --selection-batch-size 8 \
  --proposal-top-k 25 \
  --proposal-example-size 50 \
  --proposal-min-candidates 10 \
  --selection-top-mu 10 \
  --top-u 5 \
  --fluency-lambda 0.2 \
  --region-expansion-threshold 0.6

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_evoprompt10_gradpo_gen_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_10.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant gen \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_evoprompt10_gradpo_prob_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_10.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant prob \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_evoprompt10_gradpo_gen_random_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/evoprompt_de/openbookqa_non_reasoning_qwen_evoprompt_qwen14opt_lambda1/prompt_iteration_10.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant gen_random \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_lpo.py \
  --code openbookqa_non_reasoning_qwen_etgpo1_lpo_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/etgpo/openbookqa_non_reasoning_qwen_etgpo_qwen14opt_lambda1_fixed_vs1500/final_prompt.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --optimizer-model Qwen/Qwen3-14B \
  --optimizer-device cuda:0 \
  --backend vllm \
  --gpu-memory-utilization 0.90 \
  --optimizer-max-new-tokens 10000 \
  --train-sample-size 512 \
  --feedback-examples 3 \
  --max-locations 5 \
  --max-words-per-location 3 \
  --num-candidates 5 \
  --top-z 5

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_greater.py \
  --code openbookqa_non_reasoning_qwen_etgpo1_greater_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/etgpo/openbookqa_non_reasoning_qwen_etgpo_qwen14opt_lambda1_fixed_vs1500/final_prompt.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant greater \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 4 \
  --selection-batch-size 8 \
  --proposal-top-k 25 \
  --proposal-example-size 50 \
  --proposal-min-candidates 10 \
  --selection-top-mu 10 \
  --top-u 5 \
  --fluency-lambda 0.2 \
  --region-expansion-threshold 0.6

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_greater.py \
  --code openbookqa_non_reasoning_qwen_etgpo1_greater_tg_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/etgpo/openbookqa_non_reasoning_qwen_etgpo_qwen14opt_lambda1_fixed_vs1500/final_prompt.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant greater_tg \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 4 \
  --selection-batch-size 8 \
  --proposal-top-k 25 \
  --proposal-example-size 50 \
  --proposal-min-candidates 10 \
  --selection-top-mu 10 \
  --top-u 5 \
  --fluency-lambda 0.2 \
  --region-expansion-threshold 0.6

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_etgpo1_gradpo_gen_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/etgpo/openbookqa_non_reasoning_qwen_etgpo_qwen14opt_lambda1_fixed_vs1500/final_prompt.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant gen \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_etgpo1_gradpo_prob_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/etgpo/openbookqa_non_reasoning_qwen_etgpo_qwen14opt_lambda1_fixed_vs1500/final_prompt.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant prob \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4

CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=2 python -u codes/run_qa_promptopt_gradpo.py \
  --code openbookqa_non_reasoning_qwen_etgpo1_gradpo_gen_random_lambda1_vs1500 \
  --qa-task openbookqa \
  --qa-mode non_reasoning \
  --train-path data/processed/openbookqa/train.jsonl \
  --validation-path data/processed/openbookqa/validation.jsonl \
  --initial-prompt-file outputs/qa_prompt_optimization/non_reasoning/etgpo/openbookqa_non_reasoning_qwen_etgpo_qwen14opt_lambda1_fixed_vs1500/final_prompt.txt \
  --model Qwen/Qwen3-4B \
  --device cuda:0 \
  --target-max-new-tokens 10 \
  --validation-std-penalty 1.0 \
  --output-root outputs/qa_prompt_optimization \
  --overwrite \
  --backend transformers \
  --final-evaluation-backend vllm \
  --gpu-memory-utilization 0.9 \
  --variant gen_random \
  --train-sample-size 800 \
  --gradient-sample-size 200 \
  --gradient-batch-size 2 \
  --selection-batch-size 4 \
  --num-edit-regions 5 \
  --max-region-tokens 2 \
  --region-expansion-threshold 0.6 \
  --num-region-candidates 5 \
  --beam-width 5 \
  --beam-replacement-mode llm_synthesis \
  --fluency-lambda 0.5 \
  --candidate-max-new-tokens 10000 \
  --synthesis-max-new-tokens 10000 \
  --synthesis-batch-size 4
